/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.db2sampledb;
// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1


import java.util.Date;

/**
 * ClSchedId generated by hbm2java
 */
@SuppressWarnings({"serial"})
public class ClSchedId  implements java.io.Serializable {


     private String classCode;
     private Short day;
     private Date starting;
     private Date ending;

    public ClSchedId() {
    }

    public ClSchedId(String classCode, Short day, Date starting, Date ending) {
       this.classCode = classCode;
       this.day = day;
       this.starting = starting;
       this.ending = ending;
    }
   
    public String getClassCode() {
        return this.classCode;
    }
    
    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }
    public Short getDay() {
        return this.day;
    }
    
    public void setDay(Short day) {
        this.day = day;
    }
    public Date getStarting() {
        return this.starting;
    }
    
    public void setStarting(Date starting) {
        this.starting = starting;
    }
    public Date getEnding() {
        return this.ending;
    }
    
    public void setEnding(Date ending) {
        this.ending = ending;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClSchedId) ) return false;
		 ClSchedId castOther = ( ClSchedId ) other; 
         
		 return ( (this.getClassCode()==castOther.getClassCode()) || ( this.getClassCode()!=null && castOther.getClassCode()!=null && this.getClassCode().equals(castOther.getClassCode()) ) )
 && ( (this.getDay()==castOther.getDay()) || ( this.getDay()!=null && castOther.getDay()!=null && this.getDay().equals(castOther.getDay()) ) )
 && ( (this.getStarting()==castOther.getStarting()) || ( this.getStarting()!=null && castOther.getStarting()!=null && this.getStarting().equals(castOther.getStarting()) ) )
 && ( (this.getEnding()==castOther.getEnding()) || ( this.getEnding()!=null && castOther.getEnding()!=null && this.getEnding().equals(castOther.getEnding()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getClassCode() == null ? 0 : this.getClassCode().hashCode() );
         result = 37 * result + ( getDay() == null ? 0 : this.getDay().hashCode() );
         result = 37 * result + ( getStarting() == null ? 0 : this.getStarting().hashCode() );
         result = 37 * result + ( getEnding() == null ? 0 : this.getEnding().hashCode() );
         return result;
   }   


}


