/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.db2sampledb;
// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
@SuppressWarnings({"serial", "unchecked"})
public class Customer  implements java.io.Serializable {


     private long cid;
     private Serializable info;
     private Serializable history;
     private Set purchaseorders = new HashSet(0);

    public Customer() {
    }

	
    public Customer(long cid) {
        this.cid = cid;
    }
    public Customer(long cid, Serializable info, Serializable history, Set purchaseorders) {
       this.cid = cid;
       this.info = info;
       this.history = history;
       this.purchaseorders = purchaseorders;
    }
   
    public long getCid() {
        return this.cid;
    }
    
    public void setCid(long cid) {
        this.cid = cid;
    }
    public Serializable getInfo() {
        return this.info;
    }
    
    public void setInfo(Serializable info) {
        this.info = info;
    }
    public Serializable getHistory() {
        return this.history;
    }
    
    public void setHistory(Serializable history) {
        this.history = history;
    }
    public Set getPurchaseorders() {
        return this.purchaseorders;
    }
    
    public void setPurchaseorders(Set purchaseorders) {
        this.purchaseorders = purchaseorders;
    }




}


