/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.wavemaker.runtime.data.sample.db2sampledb;

// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
@SuppressWarnings({ "serial", "unchecked" })
public class Employee implements java.io.Serializable {

    private String empno;

    private Department department;

    private String firstnme;

    private Character midinit;

    private String lastname;

    private String phoneno;

    private Date hiredate;

    private String job;

    private short edlevel;

    private Character sex;

    private Date birthdate;

    private BigDecimal salary;

    private BigDecimal bonus;

    private BigDecimal comm;

    private Set departments = new HashSet(0);

    private Set empPhotos = new HashSet(0);

    private Set empResumes = new HashSet(0);

    private Set projects = new HashSet(0);

    public Employee() {
    }

    public Employee(String empno, String firstnme, String lastname, short edlevel) {
        this.empno = empno;
        this.firstnme = firstnme;
        this.lastname = lastname;
        this.edlevel = edlevel;
    }

    public Employee(String empno, Department department, String firstnme, Character midinit, String lastname, String phoneno, Date hiredate,
        String job, short edlevel, Character sex, Date birthdate, BigDecimal salary, BigDecimal bonus, BigDecimal comm, Set departments,
        Set empPhotos, Set empResumes, Set projects) {
        this.empno = empno;
        this.department = department;
        this.firstnme = firstnme;
        this.midinit = midinit;
        this.lastname = lastname;
        this.phoneno = phoneno;
        this.hiredate = hiredate;
        this.job = job;
        this.edlevel = edlevel;
        this.sex = sex;
        this.birthdate = birthdate;
        this.salary = salary;
        this.bonus = bonus;
        this.comm = comm;
        this.departments = departments;
        this.empPhotos = empPhotos;
        this.empResumes = empResumes;
        this.projects = projects;
    }

    public String getEmpno() {
        return this.empno;
    }

    public void setEmpno(String empno) {
        this.empno = empno;
    }

    public Department getDepartment() {
        return this.department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public String getFirstnme() {
        return this.firstnme;
    }

    public void setFirstnme(String firstnme) {
        this.firstnme = firstnme;
    }

    public Character getMidinit() {
        return this.midinit;
    }

    public void setMidinit(Character midinit) {
        this.midinit = midinit;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getPhoneno() {
        return this.phoneno;
    }

    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno;
    }

    public Date getHiredate() {
        return this.hiredate;
    }

    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }

    public String getJob() {
        return this.job;
    }

    public void setJob(String job) {
        this.job = job;
    }

    public short getEdlevel() {
        return this.edlevel;
    }

    public void setEdlevel(short edlevel) {
        this.edlevel = edlevel;
    }

    public Character getSex() {
        return this.sex;
    }

    public void setSex(Character sex) {
        this.sex = sex;
    }

    public Date getBirthdate() {
        return this.birthdate;
    }

    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    public BigDecimal getSalary() {
        return this.salary;
    }

    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    public BigDecimal getBonus() {
        return this.bonus;
    }

    public void setBonus(BigDecimal bonus) {
        this.bonus = bonus;
    }

    public BigDecimal getComm() {
        return this.comm;
    }

    public void setComm(BigDecimal comm) {
        this.comm = comm;
    }

    public Set getDepartments() {
        return this.departments;
    }

    public void setDepartments(Set departments) {
        this.departments = departments;
    }

    public Set getEmpPhotos() {
        return this.empPhotos;
    }

    public void setEmpPhotos(Set empPhotos) {
        this.empPhotos = empPhotos;
    }

    public Set getEmpResumes() {
        return this.empResumes;
    }

    public void setEmpResumes(Set empResumes) {
        this.empResumes = empResumes;
    }

    public Set getProjects() {
        return this.projects;
    }

    public void setProjects(Set projects) {
        this.projects = projects;
    }

}
