/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.db2sampledb;
// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1



/**
 * ProductsupplierId generated by hbm2java
 */
@SuppressWarnings({"serial"})
public class ProductsupplierId  implements java.io.Serializable {


     private String pid;
     private String sid;

    public ProductsupplierId() {
    }

    public ProductsupplierId(String pid, String sid) {
       this.pid = pid;
       this.sid = sid;
    }
   
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }
    public String getSid() {
        return this.sid;
    }
    
    public void setSid(String sid) {
        this.sid = sid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductsupplierId) ) return false;
		 ProductsupplierId castOther = ( ProductsupplierId ) other; 
         
		 return ( (this.getPid()==castOther.getPid()) || ( this.getPid()!=null && castOther.getPid()!=null && this.getPid().equals(castOther.getPid()) ) )
 && ( (this.getSid()==castOther.getSid()) || ( this.getSid()!=null && castOther.getSid()!=null && this.getSid().equals(castOther.getSid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPid() == null ? 0 : this.getPid().hashCode() );
         result = 37 * result + ( getSid() == null ? 0 : this.getSid().hashCode() );
         return result;
   }   


}


