/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.db2sampledb;
// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
@SuppressWarnings({"serial", "unchecked"})
public class Project  implements java.io.Serializable {


     private String projno;
     private Project project;
     private Employee employee;
     private Department department;
     private String projname;
     private BigDecimal prstaff;
     private Date prstdate;
     private Date prendate;
     private Set projects = new HashSet(0);
     private Set projacts = new HashSet(0);

    public Project() {
    }

	
    public Project(String projno, Employee employee, Department department, String projname) {
        this.projno = projno;
        this.employee = employee;
        this.department = department;
        this.projname = projname;
    }
    public Project(String projno, Project project, Employee employee, Department department, String projname, BigDecimal prstaff, Date prstdate, Date prendate, Set projects, Set projacts) {
       this.projno = projno;
       this.project = project;
       this.employee = employee;
       this.department = department;
       this.projname = projname;
       this.prstaff = prstaff;
       this.prstdate = prstdate;
       this.prendate = prendate;
       this.projects = projects;
       this.projacts = projacts;
    }
   
    public String getProjno() {
        return this.projno;
    }
    
    public void setProjno(String projno) {
        this.projno = projno;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public String getProjname() {
        return this.projname;
    }
    
    public void setProjname(String projname) {
        this.projname = projname;
    }
    public BigDecimal getPrstaff() {
        return this.prstaff;
    }
    
    public void setPrstaff(BigDecimal prstaff) {
        this.prstaff = prstaff;
    }
    public Date getPrstdate() {
        return this.prstdate;
    }
    
    public void setPrstdate(Date prstdate) {
        this.prstdate = prstdate;
    }
    public Date getPrendate() {
        return this.prendate;
    }
    
    public void setPrendate(Date prendate) {
        this.prendate = prendate;
    }
    public Set getProjects() {
        return this.projects;
    }
    
    public void setProjects(Set projects) {
        this.projects = projects;
    }
    public Set getProjacts() {
        return this.projacts;
    }
    
    public void setProjacts(Set projacts) {
        this.projacts = projacts;
    }




}


