/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.db2sampledb;
// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1


import java.math.BigDecimal;

/**
 * StaffId generated by hbm2java
 */
@SuppressWarnings({"serial"})
public class StaffId  implements java.io.Serializable {


     private short id;
     private String name;
     private Short dept;
     private String job;
     private Short years;
     private BigDecimal salary;
     private BigDecimal comm;

    public StaffId() {
    }

	
    public StaffId(short id) {
        this.id = id;
    }
    public StaffId(short id, String name, Short dept, String job, Short years, BigDecimal salary, BigDecimal comm) {
       this.id = id;
       this.name = name;
       this.dept = dept;
       this.job = job;
       this.years = years;
       this.salary = salary;
       this.comm = comm;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Short getDept() {
        return this.dept;
    }
    
    public void setDept(Short dept) {
        this.dept = dept;
    }
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }
    public Short getYears() {
        return this.years;
    }
    
    public void setYears(Short years) {
        this.years = years;
    }
    public BigDecimal getSalary() {
        return this.salary;
    }
    
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }
    public BigDecimal getComm() {
        return this.comm;
    }
    
    public void setComm(BigDecimal comm) {
        this.comm = comm;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StaffId) ) return false;
		 StaffId castOther = ( StaffId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getDept()==castOther.getDept()) || ( this.getDept()!=null && castOther.getDept()!=null && this.getDept().equals(castOther.getDept()) ) )
 && ( (this.getJob()==castOther.getJob()) || ( this.getJob()!=null && castOther.getJob()!=null && this.getJob().equals(castOther.getJob()) ) )
 && ( (this.getYears()==castOther.getYears()) || ( this.getYears()!=null && castOther.getYears()!=null && this.getYears().equals(castOther.getYears()) ) )
 && ( (this.getSalary()==castOther.getSalary()) || ( this.getSalary()!=null && castOther.getSalary()!=null && this.getSalary().equals(castOther.getSalary()) ) )
 && ( (this.getComm()==castOther.getComm()) || ( this.getComm()!=null && castOther.getComm()!=null && this.getComm().equals(castOther.getComm()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getDept() == null ? 0 : this.getDept().hashCode() );
         result = 37 * result + ( getJob() == null ? 0 : this.getJob().hashCode() );
         result = 37 * result + ( getYears() == null ? 0 : this.getYears().hashCode() );
         result = 37 * result + ( getSalary() == null ? 0 : this.getSalary().hashCode() );
         result = 37 * result + ( getComm() == null ? 0 : this.getComm().hashCode() );
         return result;
   }   


}


