/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.wavemaker.runtime.data.sample.db2sampledb;

// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1

/**
 * VhdeptId generated by hbm2java
 */
@SuppressWarnings({ "serial" })
public class VhdeptId implements java.io.Serializable {

    private String deptno;

    private String deptname;

    private String mgrno;

    private String admrdept;

    private String location;

    public VhdeptId() {
    }

    public VhdeptId(String deptno, String deptname, String admrdept) {
        this.deptno = deptno;
        this.deptname = deptname;
        this.admrdept = admrdept;
    }

    public VhdeptId(String deptno, String deptname, String mgrno, String admrdept, String location) {
        this.deptno = deptno;
        this.deptname = deptname;
        this.mgrno = mgrno;
        this.admrdept = admrdept;
        this.location = location;
    }

    public String getDeptno() {
        return this.deptno;
    }

    public void setDeptno(String deptno) {
        this.deptno = deptno;
    }

    public String getDeptname() {
        return this.deptname;
    }

    public void setDeptname(String deptname) {
        this.deptname = deptname;
    }

    public String getMgrno() {
        return this.mgrno;
    }

    public void setMgrno(String mgrno) {
        this.mgrno = mgrno;
    }

    public String getAdmrdept() {
        return this.admrdept;
    }

    public void setAdmrdept(String admrdept) {
        this.admrdept = admrdept;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof VhdeptId)) {
            return false;
        }
        VhdeptId castOther = (VhdeptId) other;

        return (this.getDeptno() == castOther.getDeptno() || this.getDeptno() != null && castOther.getDeptno() != null
            && this.getDeptno().equals(castOther.getDeptno()))
            && (this.getDeptname() == castOther.getDeptname() || this.getDeptname() != null && castOther.getDeptname() != null
                && this.getDeptname().equals(castOther.getDeptname()))
            && (this.getMgrno() == castOther.getMgrno() || this.getMgrno() != null && castOther.getMgrno() != null
                && this.getMgrno().equals(castOther.getMgrno()))
            && (this.getAdmrdept() == castOther.getAdmrdept() || this.getAdmrdept() != null && castOther.getAdmrdept() != null
                && this.getAdmrdept().equals(castOther.getAdmrdept()))
            && (this.getLocation() == castOther.getLocation() || this.getLocation() != null && castOther.getLocation() != null
                && this.getLocation().equals(castOther.getLocation()));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getDeptno() == null ? 0 : this.getDeptno().hashCode());
        result = 37 * result + (getDeptname() == null ? 0 : this.getDeptname().hashCode());
        result = 37 * result + (getMgrno() == null ? 0 : this.getMgrno().hashCode());
        result = 37 * result + (getAdmrdept() == null ? 0 : this.getAdmrdept().hashCode());
        result = 37 * result + (getLocation() == null ? 0 : this.getLocation().hashCode());
        return result;
    }

}
