/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.wavemaker.runtime.data.sample.db2sampledb;

// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1

/**
 * Vprojre1Id generated by hbm2java
 */
@SuppressWarnings({ "serial" })
public class Vprojre1Id implements java.io.Serializable {

    private String projno;

    private String projname;

    private String projdep;

    private String respemp;

    private String firstnme;

    private Character midinit;

    private String lastname;

    private String majproj;

    public Vprojre1Id() {
    }

    public Vprojre1Id(String projno, String projname, String projdep, String respemp, String firstnme, String lastname) {
        this.projno = projno;
        this.projname = projname;
        this.projdep = projdep;
        this.respemp = respemp;
        this.firstnme = firstnme;
        this.lastname = lastname;
    }

    public Vprojre1Id(String projno, String projname, String projdep, String respemp, String firstnme, Character midinit, String lastname,
        String majproj) {
        this.projno = projno;
        this.projname = projname;
        this.projdep = projdep;
        this.respemp = respemp;
        this.firstnme = firstnme;
        this.midinit = midinit;
        this.lastname = lastname;
        this.majproj = majproj;
    }

    public String getProjno() {
        return this.projno;
    }

    public void setProjno(String projno) {
        this.projno = projno;
    }

    public String getProjname() {
        return this.projname;
    }

    public void setProjname(String projname) {
        this.projname = projname;
    }

    public String getProjdep() {
        return this.projdep;
    }

    public void setProjdep(String projdep) {
        this.projdep = projdep;
    }

    public String getRespemp() {
        return this.respemp;
    }

    public void setRespemp(String respemp) {
        this.respemp = respemp;
    }

    public String getFirstnme() {
        return this.firstnme;
    }

    public void setFirstnme(String firstnme) {
        this.firstnme = firstnme;
    }

    public Character getMidinit() {
        return this.midinit;
    }

    public void setMidinit(Character midinit) {
        this.midinit = midinit;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getMajproj() {
        return this.majproj;
    }

    public void setMajproj(String majproj) {
        this.majproj = majproj;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof Vprojre1Id)) {
            return false;
        }
        Vprojre1Id castOther = (Vprojre1Id) other;

        return (this.getProjno() == castOther.getProjno() || this.getProjno() != null && castOther.getProjno() != null
            && this.getProjno().equals(castOther.getProjno()))
            && (this.getProjname() == castOther.getProjname() || this.getProjname() != null && castOther.getProjname() != null
                && this.getProjname().equals(castOther.getProjname()))
            && (this.getProjdep() == castOther.getProjdep() || this.getProjdep() != null && castOther.getProjdep() != null
                && this.getProjdep().equals(castOther.getProjdep()))
            && (this.getRespemp() == castOther.getRespemp() || this.getRespemp() != null && castOther.getRespemp() != null
                && this.getRespemp().equals(castOther.getRespemp()))
            && (this.getFirstnme() == castOther.getFirstnme() || this.getFirstnme() != null && castOther.getFirstnme() != null
                && this.getFirstnme().equals(castOther.getFirstnme()))
            && (this.getMidinit() == castOther.getMidinit() || this.getMidinit() != null && castOther.getMidinit() != null
                && this.getMidinit().equals(castOther.getMidinit()))
            && (this.getLastname() == castOther.getLastname() || this.getLastname() != null && castOther.getLastname() != null
                && this.getLastname().equals(castOther.getLastname()))
            && (this.getMajproj() == castOther.getMajproj() || this.getMajproj() != null && castOther.getMajproj() != null
                && this.getMajproj().equals(castOther.getMajproj()));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getProjno() == null ? 0 : this.getProjno().hashCode());
        result = 37 * result + (getProjname() == null ? 0 : this.getProjname().hashCode());
        result = 37 * result + (getProjdep() == null ? 0 : this.getProjdep().hashCode());
        result = 37 * result + (getRespemp() == null ? 0 : this.getRespemp().hashCode());
        result = 37 * result + (getFirstnme() == null ? 0 : this.getFirstnme().hashCode());
        result = 37 * result + (getMidinit() == null ? 0 : this.getMidinit().hashCode());
        result = 37 * result + (getLastname() == null ? 0 : this.getLastname().hashCode());
        result = 37 * result + (getMajproj() == null ? 0 : this.getMajproj().hashCode());
        return result;
    }

}
