/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.wavemaker.runtime.data.sample.db2sampledb;

// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * VprojId generated by hbm2java
 */
@SuppressWarnings({ "serial" })
public class VprojId implements java.io.Serializable {

    private String projno;

    private String projname;

    private String deptno;

    private String respemp;

    private BigDecimal prstaff;

    private Date prstdate;

    private Date prendate;

    private String majproj;

    public VprojId() {
    }

    public VprojId(String projno, String projname, String deptno, String respemp) {
        this.projno = projno;
        this.projname = projname;
        this.deptno = deptno;
        this.respemp = respemp;
    }

    public VprojId(String projno, String projname, String deptno, String respemp, BigDecimal prstaff, Date prstdate, Date prendate, String majproj) {
        this.projno = projno;
        this.projname = projname;
        this.deptno = deptno;
        this.respemp = respemp;
        this.prstaff = prstaff;
        this.prstdate = prstdate;
        this.prendate = prendate;
        this.majproj = majproj;
    }

    public String getProjno() {
        return this.projno;
    }

    public void setProjno(String projno) {
        this.projno = projno;
    }

    public String getProjname() {
        return this.projname;
    }

    public void setProjname(String projname) {
        this.projname = projname;
    }

    public String getDeptno() {
        return this.deptno;
    }

    public void setDeptno(String deptno) {
        this.deptno = deptno;
    }

    public String getRespemp() {
        return this.respemp;
    }

    public void setRespemp(String respemp) {
        this.respemp = respemp;
    }

    public BigDecimal getPrstaff() {
        return this.prstaff;
    }

    public void setPrstaff(BigDecimal prstaff) {
        this.prstaff = prstaff;
    }

    public Date getPrstdate() {
        return this.prstdate;
    }

    public void setPrstdate(Date prstdate) {
        this.prstdate = prstdate;
    }

    public Date getPrendate() {
        return this.prendate;
    }

    public void setPrendate(Date prendate) {
        this.prendate = prendate;
    }

    public String getMajproj() {
        return this.majproj;
    }

    public void setMajproj(String majproj) {
        this.majproj = majproj;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof VprojId)) {
            return false;
        }
        VprojId castOther = (VprojId) other;

        return (this.getProjno() == castOther.getProjno() || this.getProjno() != null && castOther.getProjno() != null
            && this.getProjno().equals(castOther.getProjno()))
            && (this.getProjname() == castOther.getProjname() || this.getProjname() != null && castOther.getProjname() != null
                && this.getProjname().equals(castOther.getProjname()))
            && (this.getDeptno() == castOther.getDeptno() || this.getDeptno() != null && castOther.getDeptno() != null
                && this.getDeptno().equals(castOther.getDeptno()))
            && (this.getRespemp() == castOther.getRespemp() || this.getRespemp() != null && castOther.getRespemp() != null
                && this.getRespemp().equals(castOther.getRespemp()))
            && (this.getPrstaff() == castOther.getPrstaff() || this.getPrstaff() != null && castOther.getPrstaff() != null
                && this.getPrstaff().equals(castOther.getPrstaff()))
            && (this.getPrstdate() == castOther.getPrstdate() || this.getPrstdate() != null && castOther.getPrstdate() != null
                && this.getPrstdate().equals(castOther.getPrstdate()))
            && (this.getPrendate() == castOther.getPrendate() || this.getPrendate() != null && castOther.getPrendate() != null
                && this.getPrendate().equals(castOther.getPrendate()))
            && (this.getMajproj() == castOther.getMajproj() || this.getMajproj() != null && castOther.getMajproj() != null
                && this.getMajproj().equals(castOther.getMajproj()));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getProjno() == null ? 0 : this.getProjno().hashCode());
        result = 37 * result + (getProjname() == null ? 0 : this.getProjname().hashCode());
        result = 37 * result + (getDeptno() == null ? 0 : this.getDeptno().hashCode());
        result = 37 * result + (getRespemp() == null ? 0 : this.getRespemp().hashCode());
        result = 37 * result + (getPrstaff() == null ? 0 : this.getPrstaff().hashCode());
        result = 37 * result + (getPrstdate() == null ? 0 : this.getPrstdate().hashCode());
        result = 37 * result + (getPrendate() == null ? 0 : this.getPrendate().hashCode());
        result = 37 * result + (getMajproj() == null ? 0 : this.getMajproj().hashCode());
        return result;
    }

}
