<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns:yahoomaps="urn:yahoo:maps"
    targetNamespace="urn:yahoo:maps">
    
    <wsdl:documentation>
        endpoint=http://api.local.yahoo.com/MapsService/V1/trafficData?appid={appid}&amp;street={street}&amp;city={city}&amp;state={state}&amp;include_map=1
    </wsdl:documentation>
    
    <wsdl:types>
        <xs:schema>
            <xs:import namespace="urn:yahoo:maps" schemaLocation="YahooTrafficDataResponse.xsd" />
        </xs:schema>
    </wsdl:types>

    <wsdl:message name="TrafficDataRequestMsg">
        <wsdl:part name="appid" type="xs:string" />
        <wsdl:part name="street" type="xs:string" />
        <wsdl:part name="city" type="xs:string" />
        <wsdl:part name="state" type="xs:string" />
    </wsdl:message>

    <wsdl:message name="TrafficDataResponseMsg">
        <wsdl:part name="body" element="yahoomaps:ResultSet" />
    </wsdl:message>

    <wsdl:portType name="YahooTraffic">
        <wsdl:operation name="getTrafficData">
            <wsdl:input message="yahoomaps:TrafficDataRequestMsg" />
            <wsdl:output message="yahoomaps:TrafficDataResponseMsg" />
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>

