/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.wavemaker.runtime.data.sample.adventure;

// Generated Aug 18, 2007 5:20:14 PM by Hibernate Tools 3.2.0.b9

/**
 * CustomerAddressId generated by hbm2java
 */
@SuppressWarnings("serial")
public class CustomerAddressId implements java.io.Serializable {

    private int customerId;

    private int addressId;

    public CustomerAddressId() {
    }

    public CustomerAddressId(int customerId, int addressId) {
        this.customerId = customerId;
        this.addressId = addressId;
    }

    public int getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    public int getAddressId() {
        return this.addressId;
    }

    public void setAddressId(int addressId) {
        this.addressId = addressId;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof CustomerAddressId)) {
            return false;
        }
        CustomerAddressId castOther = (CustomerAddressId) other;

        return this.getCustomerId() == castOther.getCustomerId() && this.getAddressId() == castOther.getAddressId();
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getCustomerId();
        result = 37 * result + this.getAddressId();
        return result;
    }

}
