/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.wavemaker.runtime.data.sample.adventure;

// Generated Aug 18, 2007 5:20:14 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * ProductModelProductDescription generated by hbm2java
 */
@SuppressWarnings("serial")
public class ProductModelProductDescription implements java.io.Serializable {

    private ProductModelProductDescriptionId id;

    private ProductDescription productDescription;

    private ProductModel productModel;

    private String rowguid;

    private Date modifiedDate;

    public ProductModelProductDescription() {
    }

    public ProductModelProductDescription(ProductModelProductDescriptionId id, ProductDescription productDescription, ProductModel productModel,
        String rowguid, Date modifiedDate) {
        this.id = id;
        this.productDescription = productDescription;
        this.productModel = productModel;
        this.rowguid = rowguid;
        this.modifiedDate = modifiedDate;
    }

    public ProductModelProductDescriptionId getId() {
        return this.id;
    }

    public void setId(ProductModelProductDescriptionId id) {
        this.id = id;
    }

    public ProductDescription getProductDescription() {
        return this.productDescription;
    }

    public void setProductDescription(ProductDescription productDescription) {
        this.productDescription = productDescription;
    }

    public ProductModel getProductModel() {
        return this.productModel;
    }

    public void setProductModel(ProductModel productModel) {
        this.productModel = productModel;
    }

    public String getRowguid() {
        return this.rowguid;
    }

    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }

    public Date getModifiedDate() {
        return this.modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

}
