/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.wavemaker.runtime.data.sample.adventure;

// Generated Aug 18, 2007 5:20:14 PM by Hibernate Tools 3.2.0.b9

/**
 * ProductModelProductDescriptionId generated by hbm2java
 */
@SuppressWarnings("serial")
public class ProductModelProductDescriptionId implements java.io.Serializable {

    private int productModelId;

    private int productDescriptionId;

    private String culture;

    public ProductModelProductDescriptionId() {
    }

    public ProductModelProductDescriptionId(int productModelId, int productDescriptionId, String culture) {
        this.productModelId = productModelId;
        this.productDescriptionId = productDescriptionId;
        this.culture = culture;
    }

    public int getProductModelId() {
        return this.productModelId;
    }

    public void setProductModelId(int productModelId) {
        this.productModelId = productModelId;
    }

    public int getProductDescriptionId() {
        return this.productDescriptionId;
    }

    public void setProductDescriptionId(int productDescriptionId) {
        this.productDescriptionId = productDescriptionId;
    }

    public String getCulture() {
        return this.culture;
    }

    public void setCulture(String culture) {
        this.culture = culture;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof ProductModelProductDescriptionId)) {
            return false;
        }
        ProductModelProductDescriptionId castOther = (ProductModelProductDescriptionId) other;

        return this.getProductModelId() == castOther.getProductModelId()
            && this.getProductDescriptionId() == castOther.getProductDescriptionId()
            && (this.getCulture() == castOther.getCulture() || this.getCulture() != null && castOther.getCulture() != null
                && this.getCulture().equals(castOther.getCulture()));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getProductModelId();
        result = 37 * result + this.getProductDescriptionId();
        result = 37 * result + (getCulture() == null ? 0 : this.getCulture().hashCode());
        return result;
    }

}
