/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.adventure;
// Generated Aug 18, 2007 5:20:14 PM by Hibernate Tools 3.2.0.b9


import java.math.BigDecimal;
import java.util.Date;

/**
 * SalesOrderDetail generated by hbm2java
 */
@SuppressWarnings("serial")
public class SalesOrderDetail  implements java.io.Serializable {


     private SalesOrderDetailId id;
     private SalesOrderHeader salesOrderHeader;
     private Product product;
     private short orderQty;
     private BigDecimal unitPrice;
     private BigDecimal unitPriceDiscount;
     private BigDecimal lineTotal;
     private String rowguid;
     private Date modifiedDate;

    public SalesOrderDetail() {
    }

    public SalesOrderDetail(SalesOrderDetailId id, SalesOrderHeader salesOrderHeader, Product product, short orderQty, BigDecimal unitPrice, BigDecimal unitPriceDiscount, BigDecimal lineTotal, String rowguid, Date modifiedDate) {
       this.id = id;
       this.salesOrderHeader = salesOrderHeader;
       this.product = product;
       this.orderQty = orderQty;
       this.unitPrice = unitPrice;
       this.unitPriceDiscount = unitPriceDiscount;
       this.lineTotal = lineTotal;
       this.rowguid = rowguid;
       this.modifiedDate = modifiedDate;
    }
   
    public SalesOrderDetailId getId() {
        return this.id;
    }
    
    public void setId(SalesOrderDetailId id) {
        this.id = id;
    }
    public SalesOrderHeader getSalesOrderHeader() {
        return this.salesOrderHeader;
    }
    
    public void setSalesOrderHeader(SalesOrderHeader salesOrderHeader) {
        this.salesOrderHeader = salesOrderHeader;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public short getOrderQty() {
        return this.orderQty;
    }
    
    public void setOrderQty(short orderQty) {
        this.orderQty = orderQty;
    }
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
    public BigDecimal getUnitPriceDiscount() {
        return this.unitPriceDiscount;
    }
    
    public void setUnitPriceDiscount(BigDecimal unitPriceDiscount) {
        this.unitPriceDiscount = unitPriceDiscount;
    }
    public BigDecimal getLineTotal() {
        return this.lineTotal;
    }
    
    public void setLineTotal(BigDecimal lineTotal) {
        this.lineTotal = lineTotal;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


