/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.adventure;
// Generated Aug 18, 2007 5:20:14 PM by Hibernate Tools 3.2.0.b9



/**
 * VgetAllCategoriesId generated by hbm2java
 */
@SuppressWarnings("serial")
public class VgetAllCategoriesId  implements java.io.Serializable {


     private String parentProductCategoryName;
     private String productCategoryName;
     private Integer productCategoryId;

    public VgetAllCategoriesId() {
    }

	
    public VgetAllCategoriesId(String parentProductCategoryName) {
        this.parentProductCategoryName = parentProductCategoryName;
    }
    public VgetAllCategoriesId(String parentProductCategoryName, String productCategoryName, Integer productCategoryId) {
       this.parentProductCategoryName = parentProductCategoryName;
       this.productCategoryName = productCategoryName;
       this.productCategoryId = productCategoryId;
    }
   
    public String getParentProductCategoryName() {
        return this.parentProductCategoryName;
    }
    
    public void setParentProductCategoryName(String parentProductCategoryName) {
        this.parentProductCategoryName = parentProductCategoryName;
    }
    public String getProductCategoryName() {
        return this.productCategoryName;
    }
    
    public void setProductCategoryName(String productCategoryName) {
        this.productCategoryName = productCategoryName;
    }
    public Integer getProductCategoryId() {
        return this.productCategoryId;
    }
    
    public void setProductCategoryId(Integer productCategoryId) {
        this.productCategoryId = productCategoryId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VgetAllCategoriesId) ) return false;
		 VgetAllCategoriesId castOther = ( VgetAllCategoriesId ) other; 
         
		 return ( (this.getParentProductCategoryName()==castOther.getParentProductCategoryName()) || ( this.getParentProductCategoryName()!=null && castOther.getParentProductCategoryName()!=null && this.getParentProductCategoryName().equals(castOther.getParentProductCategoryName()) ) )
 && ( (this.getProductCategoryName()==castOther.getProductCategoryName()) || ( this.getProductCategoryName()!=null && castOther.getProductCategoryName()!=null && this.getProductCategoryName().equals(castOther.getProductCategoryName()) ) )
 && ( (this.getProductCategoryId()==castOther.getProductCategoryId()) || ( this.getProductCategoryId()!=null && castOther.getProductCategoryId()!=null && this.getProductCategoryId().equals(castOther.getProductCategoryId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getParentProductCategoryName() == null ? 0 : this.getParentProductCategoryName().hashCode() );
         result = 37 * result + ( getProductCategoryName() == null ? 0 : this.getProductCategoryName().hashCode() );
         result = 37 * result + ( getProductCategoryId() == null ? 0 : this.getProductCategoryId().hashCode() );
         return result;
   }   


}


