/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.orahr;
// Generated Aug 19, 2007 9:06:50 PM by Hibernate Tools 3.2.0.b9


import java.util.Date;

/**
 * JobHistory generated by hbm2java
 */
@SuppressWarnings({"serial"})
public class JobHistory  implements java.io.Serializable {


     private JobHistoryId id;
     private Employees employees;
     private Departments departments;
     private Jobs jobs;
     private Date endDate;

    public JobHistory() {
    }

	
    public JobHistory(JobHistoryId id, Employees employees, Jobs jobs, Date endDate) {
        this.id = id;
        this.employees = employees;
        this.jobs = jobs;
        this.endDate = endDate;
    }
    public JobHistory(JobHistoryId id, Employees employees, Departments departments, Jobs jobs, Date endDate) {
       this.id = id;
       this.employees = employees;
       this.departments = departments;
       this.jobs = jobs;
       this.endDate = endDate;
    }
   
    public JobHistoryId getId() {
        return this.id;
    }
    
    public void setId(JobHistoryId id) {
        this.id = id;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public Departments getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Departments departments) {
        this.departments = departments;
    }
    public Jobs getJobs() {
        return this.jobs;
    }
    
    public void setJobs(Jobs jobs) {
        this.jobs = jobs;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }




}


