/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.orahr;
// Generated Aug 19, 2007 9:06:50 PM by Hibernate Tools 3.2.0.b9


import java.util.HashSet;
import java.util.Set;

/**
 * Jobs generated by hbm2java
 */
@SuppressWarnings({"serial", "unchecked"})
public class Jobs  implements java.io.Serializable {


     private String jobId;
     private String jobTitle;
     private Integer minSalary;
     private Integer maxSalary;
     private Set jobHistories = new HashSet(0);
     private Set employeeses = new HashSet(0);

    public Jobs() {
    }

	
    public Jobs(String jobId, String jobTitle) {
        this.jobId = jobId;
        this.jobTitle = jobTitle;
    }
    public Jobs(String jobId, String jobTitle, Integer minSalary, Integer maxSalary, Set jobHistories, Set employeeses) {
       this.jobId = jobId;
       this.jobTitle = jobTitle;
       this.minSalary = minSalary;
       this.maxSalary = maxSalary;
       this.jobHistories = jobHistories;
       this.employeeses = employeeses;
    }
   
    public String getJobId() {
        return this.jobId;
    }
    
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }
    public Integer getMinSalary() {
        return this.minSalary;
    }
    
    public void setMinSalary(Integer minSalary) {
        this.minSalary = minSalary;
    }
    public Integer getMaxSalary() {
        return this.maxSalary;
    }
    
    public void setMaxSalary(Integer maxSalary) {
        this.maxSalary = maxSalary;
    }
    public Set getJobHistories() {
        return this.jobHistories;
    }
    
    public void setJobHistories(Set jobHistories) {
        this.jobHistories = jobHistories;
    }
    public Set getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }




}


