/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.db2sampledb;
// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
@SuppressWarnings({"serial", "unchecked"})
public class Department  implements java.io.Serializable {


     private String deptno;
     private Department department;
     private Employee employee;
     private String deptname;
     private String location;
     private Set employees = new HashSet(0);
     private Set departments = new HashSet(0);
     private Set projects = new HashSet(0);

    public Department() {
    }

	
    public Department(String deptno, Department department, String deptname) {
        this.deptno = deptno;
        this.department = department;
        this.deptname = deptname;
    }
    public Department(String deptno, Department department, Employee employee, String deptname, String location, Set employees, Set departments, Set projects) {
       this.deptno = deptno;
       this.department = department;
       this.employee = employee;
       this.deptname = deptname;
       this.location = location;
       this.employees = employees;
       this.departments = departments;
       this.projects = projects;
    }
   
    public String getDeptno() {
        return this.deptno;
    }
    
    public void setDeptno(String deptno) {
        this.deptno = deptno;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getDeptname() {
        return this.deptname;
    }
    
    public void setDeptname(String deptname) {
        this.deptname = deptname;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }
    public Set getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set departments) {
        this.departments = departments;
    }
    public Set getProjects() {
        return this.projects;
    }
    
    public void setProjects(Set projects) {
        this.projects = projects;
    }




}


