/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.db2sampledb;
// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1



/**
 * EmpmdcId generated by hbm2java
 */
@SuppressWarnings({"serial"})
public class EmpmdcId  implements java.io.Serializable {


     private Integer empno;
     private Integer dept;
     private Integer div;

    public EmpmdcId() {
    }

    public EmpmdcId(Integer empno, Integer dept, Integer div) {
       this.empno = empno;
       this.dept = dept;
       this.div = div;
    }
   
    public Integer getEmpno() {
        return this.empno;
    }
    
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }
    public Integer getDept() {
        return this.dept;
    }
    
    public void setDept(Integer dept) {
        this.dept = dept;
    }
    public Integer getDiv() {
        return this.div;
    }
    
    public void setDiv(Integer div) {
        this.div = div;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpmdcId) ) return false;
		 EmpmdcId castOther = ( EmpmdcId ) other; 
         
		 return ( (this.getEmpno()==castOther.getEmpno()) || ( this.getEmpno()!=null && castOther.getEmpno()!=null && this.getEmpno().equals(castOther.getEmpno()) ) )
 && ( (this.getDept()==castOther.getDept()) || ( this.getDept()!=null && castOther.getDept()!=null && this.getDept().equals(castOther.getDept()) ) )
 && ( (this.getDiv()==castOther.getDiv()) || ( this.getDiv()!=null && castOther.getDiv()!=null && this.getDiv().equals(castOther.getDiv()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmpno() == null ? 0 : this.getEmpno().hashCode() );
         result = 37 * result + ( getDept() == null ? 0 : this.getDept().hashCode() );
         result = 37 * result + ( getDiv() == null ? 0 : this.getDiv().hashCode() );
         return result;
   }   


}


