/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.db2sampledb;
// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1


import java.sql.Blob;

/**
 * EmpPhoto generated by hbm2java
 */
@SuppressWarnings({"serial"})
public class EmpPhoto  implements java.io.Serializable {


     private EmpPhotoId id;
     private Employee employee;
     private Blob picture;

    public EmpPhoto() {
    }

	
    public EmpPhoto(EmpPhotoId id, Employee employee) {
        this.id = id;
        this.employee = employee;
    }
    public EmpPhoto(EmpPhotoId id, Employee employee, Blob picture) {
       this.id = id;
       this.employee = employee;
       this.picture = picture;
    }
   
    public EmpPhotoId getId() {
        return this.id;
    }
    
    public void setId(EmpPhotoId id) {
        this.id = id;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Blob getPicture() {
        return this.picture;
    }
    
    public void setPicture(Blob picture) {
        this.picture = picture;
    }




}


