/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.db2sampledb;
// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Projact generated by hbm2java
 */
@SuppressWarnings({"serial", "unchecked"})
public class Projact  implements java.io.Serializable {


     private ProjactId id;
     private Project project;
     private BigDecimal acstaff;
     private Date acendate;
     private Set empprojacts = new HashSet(0);

    public Projact() {
    }

	
    public Projact(ProjactId id, Project project) {
        this.id = id;
        this.project = project;
    }
    public Projact(ProjactId id, Project project, BigDecimal acstaff, Date acendate, Set empprojacts) {
       this.id = id;
       this.project = project;
       this.acstaff = acstaff;
       this.acendate = acendate;
       this.empprojacts = empprojacts;
    }
   
    public ProjactId getId() {
        return this.id;
    }
    
    public void setId(ProjactId id) {
        this.id = id;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public BigDecimal getAcstaff() {
        return this.acstaff;
    }
    
    public void setAcstaff(BigDecimal acstaff) {
        this.acstaff = acstaff;
    }
    public Date getAcendate() {
        return this.acendate;
    }
    
    public void setAcendate(Date acendate) {
        this.acendate = acendate;
    }
    public Set getEmpprojacts() {
        return this.empprojacts;
    }
    
    public void setEmpprojacts(Set empprojacts) {
        this.empprojacts = empprojacts;
    }




}


