/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.db2sampledb;
// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1



/**
 * Vdepmg1Id generated by hbm2java
 */
@SuppressWarnings({"serial"})
public class Vdepmg1Id  implements java.io.Serializable {


     private String deptno;
     private String deptname;
     private String mgrno;
     private String firstnme;
     private Character midinit;
     private String lastname;
     private String admrdept;

    public Vdepmg1Id() {
    }

	
    public Vdepmg1Id(String deptno, String deptname, String admrdept) {
        this.deptno = deptno;
        this.deptname = deptname;
        this.admrdept = admrdept;
    }
    public Vdepmg1Id(String deptno, String deptname, String mgrno, String firstnme, Character midinit, String lastname, String admrdept) {
       this.deptno = deptno;
       this.deptname = deptname;
       this.mgrno = mgrno;
       this.firstnme = firstnme;
       this.midinit = midinit;
       this.lastname = lastname;
       this.admrdept = admrdept;
    }
   
    public String getDeptno() {
        return this.deptno;
    }
    
    public void setDeptno(String deptno) {
        this.deptno = deptno;
    }
    public String getDeptname() {
        return this.deptname;
    }
    
    public void setDeptname(String deptname) {
        this.deptname = deptname;
    }
    public String getMgrno() {
        return this.mgrno;
    }
    
    public void setMgrno(String mgrno) {
        this.mgrno = mgrno;
    }
    public String getFirstnme() {
        return this.firstnme;
    }
    
    public void setFirstnme(String firstnme) {
        this.firstnme = firstnme;
    }
    public Character getMidinit() {
        return this.midinit;
    }
    
    public void setMidinit(Character midinit) {
        this.midinit = midinit;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getAdmrdept() {
        return this.admrdept;
    }
    
    public void setAdmrdept(String admrdept) {
        this.admrdept = admrdept;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Vdepmg1Id) ) return false;
		 Vdepmg1Id castOther = ( Vdepmg1Id ) other; 
         
		 return ( (this.getDeptno()==castOther.getDeptno()) || ( this.getDeptno()!=null && castOther.getDeptno()!=null && this.getDeptno().equals(castOther.getDeptno()) ) )
 && ( (this.getDeptname()==castOther.getDeptname()) || ( this.getDeptname()!=null && castOther.getDeptname()!=null && this.getDeptname().equals(castOther.getDeptname()) ) )
 && ( (this.getMgrno()==castOther.getMgrno()) || ( this.getMgrno()!=null && castOther.getMgrno()!=null && this.getMgrno().equals(castOther.getMgrno()) ) )
 && ( (this.getFirstnme()==castOther.getFirstnme()) || ( this.getFirstnme()!=null && castOther.getFirstnme()!=null && this.getFirstnme().equals(castOther.getFirstnme()) ) )
 && ( (this.getMidinit()==castOther.getMidinit()) || ( this.getMidinit()!=null && castOther.getMidinit()!=null && this.getMidinit().equals(castOther.getMidinit()) ) )
 && ( (this.getLastname()==castOther.getLastname()) || ( this.getLastname()!=null && castOther.getLastname()!=null && this.getLastname().equals(castOther.getLastname()) ) )
 && ( (this.getAdmrdept()==castOther.getAdmrdept()) || ( this.getAdmrdept()!=null && castOther.getAdmrdept()!=null && this.getAdmrdept().equals(castOther.getAdmrdept()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDeptno() == null ? 0 : this.getDeptno().hashCode() );
         result = 37 * result + ( getDeptname() == null ? 0 : this.getDeptname().hashCode() );
         result = 37 * result + ( getMgrno() == null ? 0 : this.getMgrno().hashCode() );
         result = 37 * result + ( getFirstnme() == null ? 0 : this.getFirstnme().hashCode() );
         result = 37 * result + ( getMidinit() == null ? 0 : this.getMidinit().hashCode() );
         result = 37 * result + ( getLastname() == null ? 0 : this.getLastname().hashCode() );
         result = 37 * result + ( getAdmrdept() == null ? 0 : this.getAdmrdept().hashCode() );
         return result;
   }   


}


