/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.db2sampledb;
// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1



/**
 * VforplaId generated by hbm2java
 */
@SuppressWarnings({"serial"})
public class VforplaId  implements java.io.Serializable {


     private String projno;
     private String projname;
     private String respemp;
     private String projdep;
     private char frstinit;
     private Character midinit;
     private String lastname;

    public VforplaId() {
    }

	
    public VforplaId(String projno, String projname, String respemp, String projdep, char frstinit, String lastname) {
        this.projno = projno;
        this.projname = projname;
        this.respemp = respemp;
        this.projdep = projdep;
        this.frstinit = frstinit;
        this.lastname = lastname;
    }
    public VforplaId(String projno, String projname, String respemp, String projdep, char frstinit, Character midinit, String lastname) {
       this.projno = projno;
       this.projname = projname;
       this.respemp = respemp;
       this.projdep = projdep;
       this.frstinit = frstinit;
       this.midinit = midinit;
       this.lastname = lastname;
    }
   
    public String getProjno() {
        return this.projno;
    }
    
    public void setProjno(String projno) {
        this.projno = projno;
    }
    public String getProjname() {
        return this.projname;
    }
    
    public void setProjname(String projname) {
        this.projname = projname;
    }
    public String getRespemp() {
        return this.respemp;
    }
    
    public void setRespemp(String respemp) {
        this.respemp = respemp;
    }
    public String getProjdep() {
        return this.projdep;
    }
    
    public void setProjdep(String projdep) {
        this.projdep = projdep;
    }
    public char getFrstinit() {
        return this.frstinit;
    }
    
    public void setFrstinit(char frstinit) {
        this.frstinit = frstinit;
    }
    public Character getMidinit() {
        return this.midinit;
    }
    
    public void setMidinit(Character midinit) {
        this.midinit = midinit;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VforplaId) ) return false;
		 VforplaId castOther = ( VforplaId ) other; 
         
		 return ( (this.getProjno()==castOther.getProjno()) || ( this.getProjno()!=null && castOther.getProjno()!=null && this.getProjno().equals(castOther.getProjno()) ) )
 && ( (this.getProjname()==castOther.getProjname()) || ( this.getProjname()!=null && castOther.getProjname()!=null && this.getProjname().equals(castOther.getProjname()) ) )
 && ( (this.getRespemp()==castOther.getRespemp()) || ( this.getRespemp()!=null && castOther.getRespemp()!=null && this.getRespemp().equals(castOther.getRespemp()) ) )
 && ( (this.getProjdep()==castOther.getProjdep()) || ( this.getProjdep()!=null && castOther.getProjdep()!=null && this.getProjdep().equals(castOther.getProjdep()) ) )
 && (this.getFrstinit()==castOther.getFrstinit())
 && ( (this.getMidinit()==castOther.getMidinit()) || ( this.getMidinit()!=null && castOther.getMidinit()!=null && this.getMidinit().equals(castOther.getMidinit()) ) )
 && ( (this.getLastname()==castOther.getLastname()) || ( this.getLastname()!=null && castOther.getLastname()!=null && this.getLastname().equals(castOther.getLastname()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProjno() == null ? 0 : this.getProjno().hashCode() );
         result = 37 * result + ( getProjname() == null ? 0 : this.getProjname().hashCode() );
         result = 37 * result + ( getRespemp() == null ? 0 : this.getRespemp().hashCode() );
         result = 37 * result + ( getProjdep() == null ? 0 : this.getProjdep().hashCode() );
         result = 37 * result + this.getFrstinit();
         result = 37 * result + ( getMidinit() == null ? 0 : this.getMidinit().hashCode() );
         result = 37 * result + ( getLastname() == null ? 0 : this.getLastname().hashCode() );
         return result;
   }   


}


