/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.db2sampledb;
// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1



/**
 * VphoneId generated by hbm2java
 */
@SuppressWarnings({"serial"})
public class VphoneId  implements java.io.Serializable {


     private String lastname;
     private String firstname;
     private Character middleinitial;
     private String phonenumber;
     private String employeenumber;
     private String deptnumber;
     private String deptname;

    public VphoneId() {
    }

	
    public VphoneId(String lastname, String firstname, String phonenumber, String employeenumber, String deptnumber, String deptname) {
        this.lastname = lastname;
        this.firstname = firstname;
        this.phonenumber = phonenumber;
        this.employeenumber = employeenumber;
        this.deptnumber = deptnumber;
        this.deptname = deptname;
    }
    public VphoneId(String lastname, String firstname, Character middleinitial, String phonenumber, String employeenumber, String deptnumber, String deptname) {
       this.lastname = lastname;
       this.firstname = firstname;
       this.middleinitial = middleinitial;
       this.phonenumber = phonenumber;
       this.employeenumber = employeenumber;
       this.deptnumber = deptnumber;
       this.deptname = deptname;
    }
   
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public Character getMiddleinitial() {
        return this.middleinitial;
    }
    
    public void setMiddleinitial(Character middleinitial) {
        this.middleinitial = middleinitial;
    }
    public String getPhonenumber() {
        return this.phonenumber;
    }
    
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }
    public String getEmployeenumber() {
        return this.employeenumber;
    }
    
    public void setEmployeenumber(String employeenumber) {
        this.employeenumber = employeenumber;
    }
    public String getDeptnumber() {
        return this.deptnumber;
    }
    
    public void setDeptnumber(String deptnumber) {
        this.deptnumber = deptnumber;
    }
    public String getDeptname() {
        return this.deptname;
    }
    
    public void setDeptname(String deptname) {
        this.deptname = deptname;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VphoneId) ) return false;
		 VphoneId castOther = ( VphoneId ) other; 
         
		 return ( (this.getLastname()==castOther.getLastname()) || ( this.getLastname()!=null && castOther.getLastname()!=null && this.getLastname().equals(castOther.getLastname()) ) )
 && ( (this.getFirstname()==castOther.getFirstname()) || ( this.getFirstname()!=null && castOther.getFirstname()!=null && this.getFirstname().equals(castOther.getFirstname()) ) )
 && ( (this.getMiddleinitial()==castOther.getMiddleinitial()) || ( this.getMiddleinitial()!=null && castOther.getMiddleinitial()!=null && this.getMiddleinitial().equals(castOther.getMiddleinitial()) ) )
 && ( (this.getPhonenumber()==castOther.getPhonenumber()) || ( this.getPhonenumber()!=null && castOther.getPhonenumber()!=null && this.getPhonenumber().equals(castOther.getPhonenumber()) ) )
 && ( (this.getEmployeenumber()==castOther.getEmployeenumber()) || ( this.getEmployeenumber()!=null && castOther.getEmployeenumber()!=null && this.getEmployeenumber().equals(castOther.getEmployeenumber()) ) )
 && ( (this.getDeptnumber()==castOther.getDeptnumber()) || ( this.getDeptnumber()!=null && castOther.getDeptnumber()!=null && this.getDeptnumber().equals(castOther.getDeptnumber()) ) )
 && ( (this.getDeptname()==castOther.getDeptname()) || ( this.getDeptname()!=null && castOther.getDeptname()!=null && this.getDeptname().equals(castOther.getDeptname()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLastname() == null ? 0 : this.getLastname().hashCode() );
         result = 37 * result + ( getFirstname() == null ? 0 : this.getFirstname().hashCode() );
         result = 37 * result + ( getMiddleinitial() == null ? 0 : this.getMiddleinitial().hashCode() );
         result = 37 * result + ( getPhonenumber() == null ? 0 : this.getPhonenumber().hashCode() );
         result = 37 * result + ( getEmployeenumber() == null ? 0 : this.getEmployeenumber().hashCode() );
         result = 37 * result + ( getDeptnumber() == null ? 0 : this.getDeptnumber().hashCode() );
         result = 37 * result + ( getDeptname() == null ? 0 : this.getDeptname().hashCode() );
         return result;
   }   


}


