/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.db2sampledb;
// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1



/**
 * Vpstrde2Id generated by hbm2java
 */
@SuppressWarnings({"serial"})
public class Vpstrde2Id  implements java.io.Serializable {


     private String proj1no;
     private String proj1name;
     private String resp1no;
     private String resp1fn;
     private Character resp1mi;
     private String resp1ln;
     private String proj2no;
     private String proj2name;
     private String resp2no;
     private String resp2fn;
     private Character resp2mi;
     private String resp2ln;

    public Vpstrde2Id() {
    }

	
    public Vpstrde2Id(String proj1no, String proj1name, String resp1no, String resp1fn, String resp1ln, String proj2no, String proj2name, String resp2no, String resp2fn, String resp2ln) {
        this.proj1no = proj1no;
        this.proj1name = proj1name;
        this.resp1no = resp1no;
        this.resp1fn = resp1fn;
        this.resp1ln = resp1ln;
        this.proj2no = proj2no;
        this.proj2name = proj2name;
        this.resp2no = resp2no;
        this.resp2fn = resp2fn;
        this.resp2ln = resp2ln;
    }
    public Vpstrde2Id(String proj1no, String proj1name, String resp1no, String resp1fn, Character resp1mi, String resp1ln, String proj2no, String proj2name, String resp2no, String resp2fn, Character resp2mi, String resp2ln) {
       this.proj1no = proj1no;
       this.proj1name = proj1name;
       this.resp1no = resp1no;
       this.resp1fn = resp1fn;
       this.resp1mi = resp1mi;
       this.resp1ln = resp1ln;
       this.proj2no = proj2no;
       this.proj2name = proj2name;
       this.resp2no = resp2no;
       this.resp2fn = resp2fn;
       this.resp2mi = resp2mi;
       this.resp2ln = resp2ln;
    }
   
    public String getProj1no() {
        return this.proj1no;
    }
    
    public void setProj1no(String proj1no) {
        this.proj1no = proj1no;
    }
    public String getProj1name() {
        return this.proj1name;
    }
    
    public void setProj1name(String proj1name) {
        this.proj1name = proj1name;
    }
    public String getResp1no() {
        return this.resp1no;
    }
    
    public void setResp1no(String resp1no) {
        this.resp1no = resp1no;
    }
    public String getResp1fn() {
        return this.resp1fn;
    }
    
    public void setResp1fn(String resp1fn) {
        this.resp1fn = resp1fn;
    }
    public Character getResp1mi() {
        return this.resp1mi;
    }
    
    public void setResp1mi(Character resp1mi) {
        this.resp1mi = resp1mi;
    }
    public String getResp1ln() {
        return this.resp1ln;
    }
    
    public void setResp1ln(String resp1ln) {
        this.resp1ln = resp1ln;
    }
    public String getProj2no() {
        return this.proj2no;
    }
    
    public void setProj2no(String proj2no) {
        this.proj2no = proj2no;
    }
    public String getProj2name() {
        return this.proj2name;
    }
    
    public void setProj2name(String proj2name) {
        this.proj2name = proj2name;
    }
    public String getResp2no() {
        return this.resp2no;
    }
    
    public void setResp2no(String resp2no) {
        this.resp2no = resp2no;
    }
    public String getResp2fn() {
        return this.resp2fn;
    }
    
    public void setResp2fn(String resp2fn) {
        this.resp2fn = resp2fn;
    }
    public Character getResp2mi() {
        return this.resp2mi;
    }
    
    public void setResp2mi(Character resp2mi) {
        this.resp2mi = resp2mi;
    }
    public String getResp2ln() {
        return this.resp2ln;
    }
    
    public void setResp2ln(String resp2ln) {
        this.resp2ln = resp2ln;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Vpstrde2Id) ) return false;
		 Vpstrde2Id castOther = ( Vpstrde2Id ) other; 
         
		 return ( (this.getProj1no()==castOther.getProj1no()) || ( this.getProj1no()!=null && castOther.getProj1no()!=null && this.getProj1no().equals(castOther.getProj1no()) ) )
 && ( (this.getProj1name()==castOther.getProj1name()) || ( this.getProj1name()!=null && castOther.getProj1name()!=null && this.getProj1name().equals(castOther.getProj1name()) ) )
 && ( (this.getResp1no()==castOther.getResp1no()) || ( this.getResp1no()!=null && castOther.getResp1no()!=null && this.getResp1no().equals(castOther.getResp1no()) ) )
 && ( (this.getResp1fn()==castOther.getResp1fn()) || ( this.getResp1fn()!=null && castOther.getResp1fn()!=null && this.getResp1fn().equals(castOther.getResp1fn()) ) )
 && ( (this.getResp1mi()==castOther.getResp1mi()) || ( this.getResp1mi()!=null && castOther.getResp1mi()!=null && this.getResp1mi().equals(castOther.getResp1mi()) ) )
 && ( (this.getResp1ln()==castOther.getResp1ln()) || ( this.getResp1ln()!=null && castOther.getResp1ln()!=null && this.getResp1ln().equals(castOther.getResp1ln()) ) )
 && ( (this.getProj2no()==castOther.getProj2no()) || ( this.getProj2no()!=null && castOther.getProj2no()!=null && this.getProj2no().equals(castOther.getProj2no()) ) )
 && ( (this.getProj2name()==castOther.getProj2name()) || ( this.getProj2name()!=null && castOther.getProj2name()!=null && this.getProj2name().equals(castOther.getProj2name()) ) )
 && ( (this.getResp2no()==castOther.getResp2no()) || ( this.getResp2no()!=null && castOther.getResp2no()!=null && this.getResp2no().equals(castOther.getResp2no()) ) )
 && ( (this.getResp2fn()==castOther.getResp2fn()) || ( this.getResp2fn()!=null && castOther.getResp2fn()!=null && this.getResp2fn().equals(castOther.getResp2fn()) ) )
 && ( (this.getResp2mi()==castOther.getResp2mi()) || ( this.getResp2mi()!=null && castOther.getResp2mi()!=null && this.getResp2mi().equals(castOther.getResp2mi()) ) )
 && ( (this.getResp2ln()==castOther.getResp2ln()) || ( this.getResp2ln()!=null && castOther.getResp2ln()!=null && this.getResp2ln().equals(castOther.getResp2ln()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProj1no() == null ? 0 : this.getProj1no().hashCode() );
         result = 37 * result + ( getProj1name() == null ? 0 : this.getProj1name().hashCode() );
         result = 37 * result + ( getResp1no() == null ? 0 : this.getResp1no().hashCode() );
         result = 37 * result + ( getResp1fn() == null ? 0 : this.getResp1fn().hashCode() );
         result = 37 * result + ( getResp1mi() == null ? 0 : this.getResp1mi().hashCode() );
         result = 37 * result + ( getResp1ln() == null ? 0 : this.getResp1ln().hashCode() );
         result = 37 * result + ( getProj2no() == null ? 0 : this.getProj2no().hashCode() );
         result = 37 * result + ( getProj2name() == null ? 0 : this.getProj2name().hashCode() );
         result = 37 * result + ( getResp2no() == null ? 0 : this.getResp2no().hashCode() );
         result = 37 * result + ( getResp2fn() == null ? 0 : this.getResp2fn().hashCode() );
         result = 37 * result + ( getResp2mi() == null ? 0 : this.getResp2mi().hashCode() );
         result = 37 * result + ( getResp2ln() == null ? 0 : this.getResp2ln().hashCode() );
         return result;
   }   


}


