/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.db2sampledb;
// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Vstafac1Id generated by hbm2java
 */
@SuppressWarnings({"serial"})
public class Vstafac1Id  implements java.io.Serializable {


     private String projno;
     private short actno;
     private String actdesc;
     private String empno;
     private String firstnme;
     private String midinit;
     private String lastname;
     private BigDecimal emptime;
     private Date stdate;
     private Date endate;
     private String type;

    public Vstafac1Id() {
    }

	
    public Vstafac1Id(String projno, short actno, String actdesc, String empno, String firstnme, String midinit, String lastname, Date stdate, String type) {
        this.projno = projno;
        this.actno = actno;
        this.actdesc = actdesc;
        this.empno = empno;
        this.firstnme = firstnme;
        this.midinit = midinit;
        this.lastname = lastname;
        this.stdate = stdate;
        this.type = type;
    }
    public Vstafac1Id(String projno, short actno, String actdesc, String empno, String firstnme, String midinit, String lastname, BigDecimal emptime, Date stdate, Date endate, String type) {
       this.projno = projno;
       this.actno = actno;
       this.actdesc = actdesc;
       this.empno = empno;
       this.firstnme = firstnme;
       this.midinit = midinit;
       this.lastname = lastname;
       this.emptime = emptime;
       this.stdate = stdate;
       this.endate = endate;
       this.type = type;
    }
   
    public String getProjno() {
        return this.projno;
    }
    
    public void setProjno(String projno) {
        this.projno = projno;
    }
    public short getActno() {
        return this.actno;
    }
    
    public void setActno(short actno) {
        this.actno = actno;
    }
    public String getActdesc() {
        return this.actdesc;
    }
    
    public void setActdesc(String actdesc) {
        this.actdesc = actdesc;
    }
    public String getEmpno() {
        return this.empno;
    }
    
    public void setEmpno(String empno) {
        this.empno = empno;
    }
    public String getFirstnme() {
        return this.firstnme;
    }
    
    public void setFirstnme(String firstnme) {
        this.firstnme = firstnme;
    }
    public String getMidinit() {
        return this.midinit;
    }
    
    public void setMidinit(String midinit) {
        this.midinit = midinit;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public BigDecimal getEmptime() {
        return this.emptime;
    }
    
    public void setEmptime(BigDecimal emptime) {
        this.emptime = emptime;
    }
    public Date getStdate() {
        return this.stdate;
    }
    
    public void setStdate(Date stdate) {
        this.stdate = stdate;
    }
    public Date getEndate() {
        return this.endate;
    }
    
    public void setEndate(Date endate) {
        this.endate = endate;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Vstafac1Id) ) return false;
		 Vstafac1Id castOther = ( Vstafac1Id ) other; 
         
		 return ( (this.getProjno()==castOther.getProjno()) || ( this.getProjno()!=null && castOther.getProjno()!=null && this.getProjno().equals(castOther.getProjno()) ) )
 && (this.getActno()==castOther.getActno())
 && ( (this.getActdesc()==castOther.getActdesc()) || ( this.getActdesc()!=null && castOther.getActdesc()!=null && this.getActdesc().equals(castOther.getActdesc()) ) )
 && ( (this.getEmpno()==castOther.getEmpno()) || ( this.getEmpno()!=null && castOther.getEmpno()!=null && this.getEmpno().equals(castOther.getEmpno()) ) )
 && ( (this.getFirstnme()==castOther.getFirstnme()) || ( this.getFirstnme()!=null && castOther.getFirstnme()!=null && this.getFirstnme().equals(castOther.getFirstnme()) ) )
 && ( (this.getMidinit()==castOther.getMidinit()) || ( this.getMidinit()!=null && castOther.getMidinit()!=null && this.getMidinit().equals(castOther.getMidinit()) ) )
 && ( (this.getLastname()==castOther.getLastname()) || ( this.getLastname()!=null && castOther.getLastname()!=null && this.getLastname().equals(castOther.getLastname()) ) )
 && ( (this.getEmptime()==castOther.getEmptime()) || ( this.getEmptime()!=null && castOther.getEmptime()!=null && this.getEmptime().equals(castOther.getEmptime()) ) )
 && ( (this.getStdate()==castOther.getStdate()) || ( this.getStdate()!=null && castOther.getStdate()!=null && this.getStdate().equals(castOther.getStdate()) ) )
 && ( (this.getEndate()==castOther.getEndate()) || ( this.getEndate()!=null && castOther.getEndate()!=null && this.getEndate().equals(castOther.getEndate()) ) )
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProjno() == null ? 0 : this.getProjno().hashCode() );
         result = 37 * result + this.getActno();
         result = 37 * result + ( getActdesc() == null ? 0 : this.getActdesc().hashCode() );
         result = 37 * result + ( getEmpno() == null ? 0 : this.getEmpno().hashCode() );
         result = 37 * result + ( getFirstnme() == null ? 0 : this.getFirstnme().hashCode() );
         result = 37 * result + ( getMidinit() == null ? 0 : this.getMidinit().hashCode() );
         result = 37 * result + ( getLastname() == null ? 0 : this.getLastname().hashCode() );
         result = 37 * result + ( getEmptime() == null ? 0 : this.getEmptime().hashCode() );
         result = 37 * result + ( getStdate() == null ? 0 : this.getStdate().hashCode() );
         result = 37 * result + ( getEndate() == null ? 0 : this.getEndate().hashCode() );
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         return result;
   }   


}


