DROP SCHEMA IF EXISTS aghr;
CREATE SCHEMA aghr;
USE aghr;

CREATE TABLE employee (
  employee_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  PRIMARY KEY  (employee_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE compkey (
  id1 SMALLINT UNSIGNED NOT NULL,
  id2 SMALLINT UNSIGNED NOT NULL,
  name VARCHAR(45),
  PRIMARY KEY  (id1, id2)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE person (
  id SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
  first_name VARCHAR(45),
  last_name VARCHAR(45) NOT NULL,
  email VARCHAR(45)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
