/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.wavemaker.runtime.data.sample.db2sampledb;

// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Act generated by hbm2java
 */
@SuppressWarnings({ "serial", "unchecked" })
public class Act implements java.io.Serializable {

    private short actno;

    private Act act;

    private String actkwd;

    private String actdesc;

    private Set acts = new HashSet(0);

    public Act() {
    }

    public Act(short actno, Act act, String actkwd, String actdesc) {
        this.actno = actno;
        this.act = act;
        this.actkwd = actkwd;
        this.actdesc = actdesc;
    }

    public Act(short actno, Act act, String actkwd, String actdesc, Set acts) {
        this.actno = actno;
        this.act = act;
        this.actkwd = actkwd;
        this.actdesc = actdesc;
        this.acts = acts;
    }

    public short getActno() {
        return this.actno;
    }

    public void setActno(short actno) {
        this.actno = actno;
    }

    public Act getAct() {
        return this.act;
    }

    public void setAct(Act act) {
        this.act = act;
    }

    public String getActkwd() {
        return this.actkwd;
    }

    public void setActkwd(String actkwd) {
        this.actkwd = actkwd;
    }

    public String getActdesc() {
        return this.actdesc;
    }

    public void setActdesc(String actdesc) {
        this.actdesc = actdesc;
    }

    public Set getActs() {
        return this.acts;
    }

    public void setActs(Set acts) {
        this.acts = acts;
    }

}
