/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.wavemaker.runtime.data.sample.db2sampledb;

// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;

/**
 * InTrayId generated by hbm2java
 */
@SuppressWarnings({ "serial" })
public class InTrayId implements java.io.Serializable {

    private Date received;

    private String source;

    private String subject;

    private String noteText;

    public InTrayId() {
    }

    public InTrayId(Date received, String source, String subject, String noteText) {
        this.received = received;
        this.source = source;
        this.subject = subject;
        this.noteText = noteText;
    }

    public Date getReceived() {
        return this.received;
    }

    public void setReceived(Date received) {
        this.received = received;
    }

    public String getSource() {
        return this.source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getSubject() {
        return this.subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getNoteText() {
        return this.noteText;
    }

    public void setNoteText(String noteText) {
        this.noteText = noteText;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof InTrayId)) {
            return false;
        }
        InTrayId castOther = (InTrayId) other;

        return (this.getReceived() == castOther.getReceived() || this.getReceived() != null && castOther.getReceived() != null
            && this.getReceived().equals(castOther.getReceived()))
            && (this.getSource() == castOther.getSource() || this.getSource() != null && castOther.getSource() != null
                && this.getSource().equals(castOther.getSource()))
            && (this.getSubject() == castOther.getSubject() || this.getSubject() != null && castOther.getSubject() != null
                && this.getSubject().equals(castOther.getSubject()))
            && (this.getNoteText() == castOther.getNoteText() || this.getNoteText() != null && castOther.getNoteText() != null
                && this.getNoteText().equals(castOther.getNoteText()));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getReceived() == null ? 0 : this.getReceived().hashCode());
        result = 37 * result + (getSource() == null ? 0 : this.getSource().hashCode());
        result = 37 * result + (getSubject() == null ? 0 : this.getSubject().hashCode());
        result = 37 * result + (getNoteText() == null ? 0 : this.getNoteText().hashCode());
        return result;
    }

}
