/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.wavemaker.runtime.data.sample.db2sampledb;

// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1

/**
 * OrgId generated by hbm2java
 */
@SuppressWarnings({ "serial" })
public class OrgId implements java.io.Serializable {

    private short deptnumb;

    private String deptname;

    private Short manager;

    private String division;

    private String location;

    public OrgId() {
    }

    public OrgId(short deptnumb) {
        this.deptnumb = deptnumb;
    }

    public OrgId(short deptnumb, String deptname, Short manager, String division, String location) {
        this.deptnumb = deptnumb;
        this.deptname = deptname;
        this.manager = manager;
        this.division = division;
        this.location = location;
    }

    public short getDeptnumb() {
        return this.deptnumb;
    }

    public void setDeptnumb(short deptnumb) {
        this.deptnumb = deptnumb;
    }

    public String getDeptname() {
        return this.deptname;
    }

    public void setDeptname(String deptname) {
        this.deptname = deptname;
    }

    public Short getManager() {
        return this.manager;
    }

    public void setManager(Short manager) {
        this.manager = manager;
    }

    public String getDivision() {
        return this.division;
    }

    public void setDivision(String division) {
        this.division = division;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof OrgId)) {
            return false;
        }
        OrgId castOther = (OrgId) other;

        return this.getDeptnumb() == castOther.getDeptnumb()
            && (this.getDeptname() == castOther.getDeptname() || this.getDeptname() != null && castOther.getDeptname() != null
                && this.getDeptname().equals(castOther.getDeptname()))
            && (this.getManager() == castOther.getManager() || this.getManager() != null && castOther.getManager() != null
                && this.getManager().equals(castOther.getManager()))
            && (this.getDivision() == castOther.getDivision() || this.getDivision() != null && castOther.getDivision() != null
                && this.getDivision().equals(castOther.getDivision()))
            && (this.getLocation() == castOther.getLocation() || this.getLocation() != null && castOther.getLocation() != null
                && this.getLocation().equals(castOther.getLocation()));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getDeptnumb();
        result = 37 * result + (getDeptname() == null ? 0 : this.getDeptname().hashCode());
        result = 37 * result + (getManager() == null ? 0 : this.getManager().hashCode());
        result = 37 * result + (getDivision() == null ? 0 : this.getDivision().hashCode());
        result = 37 * result + (getLocation() == null ? 0 : this.getLocation().hashCode());
        return result;
    }

}
