/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.wavemaker.runtime.data.sample.db2sampledb;

// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Product generated by hbm2java
 */
@SuppressWarnings({ "serial" })
public class Product implements java.io.Serializable {

    private String pid;

    private String name;

    private BigDecimal price;

    private BigDecimal promoprice;

    private Date promostart;

    private Date promoend;

    private Serializable description;

    public Product() {
    }

    public Product(String pid) {
        this.pid = pid;
    }

    public Product(String pid, String name, BigDecimal price, BigDecimal promoprice, Date promostart, Date promoend, Serializable description) {
        this.pid = pid;
        this.name = name;
        this.price = price;
        this.promoprice = promoprice;
        this.promostart = promostart;
        this.promoend = promoend;
        this.description = description;
    }

    public String getPid() {
        return this.pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public BigDecimal getPromoprice() {
        return this.promoprice;
    }

    public void setPromoprice(BigDecimal promoprice) {
        this.promoprice = promoprice;
    }

    public Date getPromostart() {
        return this.promostart;
    }

    public void setPromostart(Date promostart) {
        this.promostart = promostart;
    }

    public Date getPromoend() {
        return this.promoend;
    }

    public void setPromoend(Date promoend) {
        this.promoend = promoend;
    }

    public Serializable getDescription() {
        return this.description;
    }

    public void setDescription(Serializable description) {
        this.description = description;
    }

}
