/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.wavemaker.runtime.data.sample.db2sampledb;

// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1

/**
 * VactId generated by hbm2java
 */
@SuppressWarnings({ "serial" })
public class VactId implements java.io.Serializable {

    private short actno;

    private String actkwd;

    private String actdesc;

    public VactId() {
    }

    public VactId(short actno, String actkwd, String actdesc) {
        this.actno = actno;
        this.actkwd = actkwd;
        this.actdesc = actdesc;
    }

    public short getActno() {
        return this.actno;
    }

    public void setActno(short actno) {
        this.actno = actno;
    }

    public String getActkwd() {
        return this.actkwd;
    }

    public void setActkwd(String actkwd) {
        this.actkwd = actkwd;
    }

    public String getActdesc() {
        return this.actdesc;
    }

    public void setActdesc(String actdesc) {
        this.actdesc = actdesc;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof VactId)) {
            return false;
        }
        VactId castOther = (VactId) other;

        return this.getActno() == castOther.getActno()
            && (this.getActkwd() == castOther.getActkwd() || this.getActkwd() != null && castOther.getActkwd() != null
                && this.getActkwd().equals(castOther.getActkwd()))
            && (this.getActdesc() == castOther.getActdesc() || this.getActdesc() != null && castOther.getActdesc() != null
                && this.getActdesc().equals(castOther.getActdesc()));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getActno();
        result = 37 * result + (getActkwd() == null ? 0 : this.getActkwd().hashCode());
        result = 37 * result + (getActdesc() == null ? 0 : this.getActdesc().hashCode());
        return result;
    }

}
