/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.wavemaker.runtime.data.sample.db2sampledb;

// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1

/**
 * Vastrde1Id generated by hbm2java
 */
@SuppressWarnings({ "serial" })
public class Vastrde1Id implements java.io.Serializable {

    private String dept1no;

    private String dept1nam;

    private String emp1no;

    private String emp1fn;

    private Character emp1mi;

    private String emp1ln;

    private String type2;

    private String dept2no;

    private String dept2nam;

    private String emp2no;

    private String emp2fn;

    private Character emp2mi;

    private String emp2ln;

    public Vastrde1Id() {
    }

    public Vastrde1Id(String dept1no, String dept1nam, String type2, String dept2no, String dept2nam) {
        this.dept1no = dept1no;
        this.dept1nam = dept1nam;
        this.type2 = type2;
        this.dept2no = dept2no;
        this.dept2nam = dept2nam;
    }

    public Vastrde1Id(String dept1no, String dept1nam, String emp1no, String emp1fn, Character emp1mi, String emp1ln, String type2, String dept2no,
        String dept2nam, String emp2no, String emp2fn, Character emp2mi, String emp2ln) {
        this.dept1no = dept1no;
        this.dept1nam = dept1nam;
        this.emp1no = emp1no;
        this.emp1fn = emp1fn;
        this.emp1mi = emp1mi;
        this.emp1ln = emp1ln;
        this.type2 = type2;
        this.dept2no = dept2no;
        this.dept2nam = dept2nam;
        this.emp2no = emp2no;
        this.emp2fn = emp2fn;
        this.emp2mi = emp2mi;
        this.emp2ln = emp2ln;
    }

    public String getDept1no() {
        return this.dept1no;
    }

    public void setDept1no(String dept1no) {
        this.dept1no = dept1no;
    }

    public String getDept1nam() {
        return this.dept1nam;
    }

    public void setDept1nam(String dept1nam) {
        this.dept1nam = dept1nam;
    }

    public String getEmp1no() {
        return this.emp1no;
    }

    public void setEmp1no(String emp1no) {
        this.emp1no = emp1no;
    }

    public String getEmp1fn() {
        return this.emp1fn;
    }

    public void setEmp1fn(String emp1fn) {
        this.emp1fn = emp1fn;
    }

    public Character getEmp1mi() {
        return this.emp1mi;
    }

    public void setEmp1mi(Character emp1mi) {
        this.emp1mi = emp1mi;
    }

    public String getEmp1ln() {
        return this.emp1ln;
    }

    public void setEmp1ln(String emp1ln) {
        this.emp1ln = emp1ln;
    }

    public String getType2() {
        return this.type2;
    }

    public void setType2(String type2) {
        this.type2 = type2;
    }

    public String getDept2no() {
        return this.dept2no;
    }

    public void setDept2no(String dept2no) {
        this.dept2no = dept2no;
    }

    public String getDept2nam() {
        return this.dept2nam;
    }

    public void setDept2nam(String dept2nam) {
        this.dept2nam = dept2nam;
    }

    public String getEmp2no() {
        return this.emp2no;
    }

    public void setEmp2no(String emp2no) {
        this.emp2no = emp2no;
    }

    public String getEmp2fn() {
        return this.emp2fn;
    }

    public void setEmp2fn(String emp2fn) {
        this.emp2fn = emp2fn;
    }

    public Character getEmp2mi() {
        return this.emp2mi;
    }

    public void setEmp2mi(Character emp2mi) {
        this.emp2mi = emp2mi;
    }

    public String getEmp2ln() {
        return this.emp2ln;
    }

    public void setEmp2ln(String emp2ln) {
        this.emp2ln = emp2ln;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof Vastrde1Id)) {
            return false;
        }
        Vastrde1Id castOther = (Vastrde1Id) other;

        return (this.getDept1no() == castOther.getDept1no() || this.getDept1no() != null && castOther.getDept1no() != null
            && this.getDept1no().equals(castOther.getDept1no()))
            && (this.getDept1nam() == castOther.getDept1nam() || this.getDept1nam() != null && castOther.getDept1nam() != null
                && this.getDept1nam().equals(castOther.getDept1nam()))
            && (this.getEmp1no() == castOther.getEmp1no() || this.getEmp1no() != null && castOther.getEmp1no() != null
                && this.getEmp1no().equals(castOther.getEmp1no()))
            && (this.getEmp1fn() == castOther.getEmp1fn() || this.getEmp1fn() != null && castOther.getEmp1fn() != null
                && this.getEmp1fn().equals(castOther.getEmp1fn()))
            && (this.getEmp1mi() == castOther.getEmp1mi() || this.getEmp1mi() != null && castOther.getEmp1mi() != null
                && this.getEmp1mi().equals(castOther.getEmp1mi()))
            && (this.getEmp1ln() == castOther.getEmp1ln() || this.getEmp1ln() != null && castOther.getEmp1ln() != null
                && this.getEmp1ln().equals(castOther.getEmp1ln()))
            && (this.getType2() == castOther.getType2() || this.getType2() != null && castOther.getType2() != null
                && this.getType2().equals(castOther.getType2()))
            && (this.getDept2no() == castOther.getDept2no() || this.getDept2no() != null && castOther.getDept2no() != null
                && this.getDept2no().equals(castOther.getDept2no()))
            && (this.getDept2nam() == castOther.getDept2nam() || this.getDept2nam() != null && castOther.getDept2nam() != null
                && this.getDept2nam().equals(castOther.getDept2nam()))
            && (this.getEmp2no() == castOther.getEmp2no() || this.getEmp2no() != null && castOther.getEmp2no() != null
                && this.getEmp2no().equals(castOther.getEmp2no()))
            && (this.getEmp2fn() == castOther.getEmp2fn() || this.getEmp2fn() != null && castOther.getEmp2fn() != null
                && this.getEmp2fn().equals(castOther.getEmp2fn()))
            && (this.getEmp2mi() == castOther.getEmp2mi() || this.getEmp2mi() != null && castOther.getEmp2mi() != null
                && this.getEmp2mi().equals(castOther.getEmp2mi()))
            && (this.getEmp2ln() == castOther.getEmp2ln() || this.getEmp2ln() != null && castOther.getEmp2ln() != null
                && this.getEmp2ln().equals(castOther.getEmp2ln()));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getDept1no() == null ? 0 : this.getDept1no().hashCode());
        result = 37 * result + (getDept1nam() == null ? 0 : this.getDept1nam().hashCode());
        result = 37 * result + (getEmp1no() == null ? 0 : this.getEmp1no().hashCode());
        result = 37 * result + (getEmp1fn() == null ? 0 : this.getEmp1fn().hashCode());
        result = 37 * result + (getEmp1mi() == null ? 0 : this.getEmp1mi().hashCode());
        result = 37 * result + (getEmp1ln() == null ? 0 : this.getEmp1ln().hashCode());
        result = 37 * result + (getType2() == null ? 0 : this.getType2().hashCode());
        result = 37 * result + (getDept2no() == null ? 0 : this.getDept2no().hashCode());
        result = 37 * result + (getDept2nam() == null ? 0 : this.getDept2nam().hashCode());
        result = 37 * result + (getEmp2no() == null ? 0 : this.getEmp2no().hashCode());
        result = 37 * result + (getEmp2fn() == null ? 0 : this.getEmp2fn().hashCode());
        result = 37 * result + (getEmp2mi() == null ? 0 : this.getEmp2mi().hashCode());
        result = 37 * result + (getEmp2ln() == null ? 0 : this.getEmp2ln().hashCode());
        return result;
    }

}
