/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.wavemaker.runtime.data.sample.db2sampledb;

// Generated Feb 7, 2008 1:47:51 PM by Hibernate Tools 3.2.0.CR1

/**
 * Vempdpt1Id generated by hbm2java
 */
@SuppressWarnings({ "serial" })
public class Vempdpt1Id implements java.io.Serializable {

    private String deptno;

    private String deptname;

    private String empno;

    private char frstinit;

    private Character midinit;

    private String lastname;

    private String workdept;

    public Vempdpt1Id() {
    }

    public Vempdpt1Id(String empno, char frstinit, String lastname) {
        this.empno = empno;
        this.frstinit = frstinit;
        this.lastname = lastname;
    }

    public Vempdpt1Id(String deptno, String deptname, String empno, char frstinit, Character midinit, String lastname, String workdept) {
        this.deptno = deptno;
        this.deptname = deptname;
        this.empno = empno;
        this.frstinit = frstinit;
        this.midinit = midinit;
        this.lastname = lastname;
        this.workdept = workdept;
    }

    public String getDeptno() {
        return this.deptno;
    }

    public void setDeptno(String deptno) {
        this.deptno = deptno;
    }

    public String getDeptname() {
        return this.deptname;
    }

    public void setDeptname(String deptname) {
        this.deptname = deptname;
    }

    public String getEmpno() {
        return this.empno;
    }

    public void setEmpno(String empno) {
        this.empno = empno;
    }

    public char getFrstinit() {
        return this.frstinit;
    }

    public void setFrstinit(char frstinit) {
        this.frstinit = frstinit;
    }

    public Character getMidinit() {
        return this.midinit;
    }

    public void setMidinit(Character midinit) {
        this.midinit = midinit;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getWorkdept() {
        return this.workdept;
    }

    public void setWorkdept(String workdept) {
        this.workdept = workdept;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof Vempdpt1Id)) {
            return false;
        }
        Vempdpt1Id castOther = (Vempdpt1Id) other;

        return (this.getDeptno() == castOther.getDeptno() || this.getDeptno() != null && castOther.getDeptno() != null
            && this.getDeptno().equals(castOther.getDeptno()))
            && (this.getDeptname() == castOther.getDeptname() || this.getDeptname() != null && castOther.getDeptname() != null
                && this.getDeptname().equals(castOther.getDeptname()))
            && (this.getEmpno() == castOther.getEmpno() || this.getEmpno() != null && castOther.getEmpno() != null
                && this.getEmpno().equals(castOther.getEmpno()))
            && this.getFrstinit() == castOther.getFrstinit()
            && (this.getMidinit() == castOther.getMidinit() || this.getMidinit() != null && castOther.getMidinit() != null
                && this.getMidinit().equals(castOther.getMidinit()))
            && (this.getLastname() == castOther.getLastname() || this.getLastname() != null && castOther.getLastname() != null
                && this.getLastname().equals(castOther.getLastname()))
            && (this.getWorkdept() == castOther.getWorkdept() || this.getWorkdept() != null && castOther.getWorkdept() != null
                && this.getWorkdept().equals(castOther.getWorkdept()));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getDeptno() == null ? 0 : this.getDeptno().hashCode());
        result = 37 * result + (getDeptname() == null ? 0 : this.getDeptname().hashCode());
        result = 37 * result + (getEmpno() == null ? 0 : this.getEmpno().hashCode());
        result = 37 * result + this.getFrstinit();
        result = 37 * result + (getMidinit() == null ? 0 : this.getMidinit().hashCode());
        result = 37 * result + (getLastname() == null ? 0 : this.getLastname().hashCode());
        result = 37 * result + (getWorkdept() == null ? 0 : this.getWorkdept().hashCode());
        return result;
    }

}
