/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.sakila;
// Generated Jun 26, 2007 4:52:50 PM by Hibernate Tools 3.2.0.b9


import java.util.Date;

/**
 * FilmActor generated by hbm2java
 */
@SuppressWarnings({"serial"})
public class TestFilmActor  implements java.io.Serializable {


     private FilmActorId id;
     private TestFilm film;
     private TestActor actor;
     private Date lastUpdate;

    public TestFilmActor() {
    }

    public TestFilmActor(FilmActorId id, TestFilm film, TestActor actor, Date lastUpdate) {
       this.id = id;
       this.film = film;
       this.actor = actor;
       this.lastUpdate = lastUpdate;
    }
   
    public FilmActorId getId() {
        return this.id;
    }
    
    public void setId(FilmActorId id) {
        this.id = id;
    }
    public TestFilm getFilm() {
        return this.film;
    }
    
    public void setFilm(TestFilm film) {
        this.film = film;
    }
    public TestActor getActor() {
        return this.actor;
    }
    
    public void setActor(TestActor actor) {
        this.actor = actor;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


