//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.06 at 01:44:45 PM PST 
//


package com.wavemaker.tools.security.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for named-security-filter.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="named-security-filter">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="FIRST"/>
 *     &lt;enumeration value="CHANNEL_FILTER"/>
 *     &lt;enumeration value="CONCURRENT_SESSION_FILTER"/>
 *     &lt;enumeration value="SECURITY_CONTEXT_FILTER"/>
 *     &lt;enumeration value="LOGOUT_FILTER"/>
 *     &lt;enumeration value="X509_FILTER"/>
 *     &lt;enumeration value="PRE_AUTH_FILTER"/>
 *     &lt;enumeration value="CAS_FILTER"/>
 *     &lt;enumeration value="FORM_LOGIN_FILTER"/>
 *     &lt;enumeration value="OPENID_FILTER"/>
 *     &lt;enumeration value="BASIC_AUTH_FILTER"/>
 *     &lt;enumeration value="SERVLET_API_SUPPORT_FILTER"/>
 *     &lt;enumeration value="REMEMBER_ME_FILTER"/>
 *     &lt;enumeration value="ANONYMOUS_FILTER"/>
 *     &lt;enumeration value="EXCEPTION_TRANSLATION_FILTER"/>
 *     &lt;enumeration value="SESSION_MANAGEMENT_FILTER"/>
 *     &lt;enumeration value="FILTER_SECURITY_INTERCEPTOR"/>
 *     &lt;enumeration value="SWITCH_USER_FILTER"/>
 *     &lt;enumeration value="LAST"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "named-security-filter")
@XmlEnum
public enum NamedSecurityFilter {

    FIRST("FIRST"),
    CHANNEL_FILTER("CHANNEL_FILTER"),
    CONCURRENT_SESSION_FILTER("CONCURRENT_SESSION_FILTER"),
    SECURITY_CONTEXT_FILTER("SECURITY_CONTEXT_FILTER"),
    LOGOUT_FILTER("LOGOUT_FILTER"),
    @XmlEnumValue("X509_FILTER")
    X_509_FILTER("X509_FILTER"),
    PRE_AUTH_FILTER("PRE_AUTH_FILTER"),
    CAS_FILTER("CAS_FILTER"),
    FORM_LOGIN_FILTER("FORM_LOGIN_FILTER"),
    OPENID_FILTER("OPENID_FILTER"),
    BASIC_AUTH_FILTER("BASIC_AUTH_FILTER"),
    SERVLET_API_SUPPORT_FILTER("SERVLET_API_SUPPORT_FILTER"),
    REMEMBER_ME_FILTER("REMEMBER_ME_FILTER"),
    ANONYMOUS_FILTER("ANONYMOUS_FILTER"),
    EXCEPTION_TRANSLATION_FILTER("EXCEPTION_TRANSLATION_FILTER"),
    SESSION_MANAGEMENT_FILTER("SESSION_MANAGEMENT_FILTER"),
    FILTER_SECURITY_INTERCEPTOR("FILTER_SECURITY_INTERCEPTOR"),
    SWITCH_USER_FILTER("SWITCH_USER_FILTER"),
    LAST("LAST");
    private final String value;

    NamedSecurityFilter(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NamedSecurityFilter fromValue(String v) {
        for (NamedSecurityFilter c: NamedSecurityFilter.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
