dojo.provide("lib.github.touchscroll.touchscroll");
function CubicBezier(c,e,h,f){if(!(0<=c&&1>=c))throw new RangeError("'p1x' must be a number between 0 and 1. Got "+c+"instead.");if(!(0<=e&&1>=e))throw new RangeError("'p1y' must be a number between 0 and 1. Got "+e+"instead.");if(!(0<=h&&1>=h))throw new RangeError("'p2x' must be a number between 0 and 1. Got "+h+"instead.");if(!(0<=f&&1>=f))throw new RangeError("'p2y' must be a number between 0 and 1. Got "+f+"instead.");this._p1={x:c,y:e};this._p2={x:h,y:f}}
CubicBezier.prototype._getCoordinateForT=function(c,e,h){var f=3*e,e=3*(h-e)-f;return(((1-f-e)*c+e)*c+f)*c};CubicBezier.prototype._getCoordinateDerivateForT=function(c,e,h){var f=3*e,e=3*(h-e)-f;return(3*(1-f-e)*c+2*e)*c+f};
CubicBezier.prototype._getTForCoordinate=function(c,e,h,f){if(!isFinite(f)||0>=f)throw new RangeError("'epsilon' must be a number greater than 0.");for(var i=c,m=0,j,l;8>m;m++){j=this._getCoordinateForT(i,e,h)-c;if(Math.abs(j)<f)return i;l=this._getCoordinateDerivateForT(i,e,h);if(1.0E-6>Math.abs(l))break;i-=j/l}i=c;m=0;l=1;if(i<m)return m;if(i>l)return l;for(;m<l;){j=this._getCoordinateForT(i,e,h);if(Math.abs(j-c)<f)break;c>j?m=i:l=i;i=0.5*(l-m)+m}return i};
CubicBezier.prototype.getPointForT=function(c){if(0==c||1==c)return{x:c,y:c};if(!(0<c)||!(1>c))throw new RangeError("'t' must be a number between 0 and 1Got "+c+" instead.");return{x:this._getCoordinateForT(c,this._p1.x,this._p2.x),y:this._getCoordinateForT(c,this._p1.y,this._p2.y)}};CubicBezier.prototype.getTforX=function(c,e){return this._getTForCoordinate(c,this._p1.x,this._p2.x,e)};CubicBezier.prototype.getTforY=function(c,e){return this._getTForCoordinate(c,this._p1.y,this._p2.y,e)};
CubicBezier.prototype._getAuxPoints=function(c){if(!(0<c)||!(1>c))throw new RangeError("'t' must be greater than 0 and lower than 1");var e={x:c*this._p1.x,y:c*this._p1.y},h={x:this._p1.x+c*(this._p2.x-this._p1.x),y:this._p1.y+c*(this._p2.y-this._p1.y)},f={x:this._p2.x+c*(1-this._p2.x),y:this._p2.y+c*(1-this._p2.y)},i={x:e.x+c*(h.x-e.x),y:e.y+c*(h.y-e.y)},m={x:h.x+c*(f.x-h.x),y:h.y+c*(f.y-h.y)};return{i0:e,i1:h,i2:f,j0:i,j1:m,k:{x:i.x+c*(m.x-i.x),y:i.y+c*(m.y-i.y)}}};
CubicBezier.prototype.divideAtT=function(c){var e,h,f,i,m,j,l;if(0>c||1<c)throw new RangeError("'t' must be a number between 0 and 1. Got "+c+" instead.");if(0===c||1===c)return j=[],j[c]=CubicBezier.linear(),j[1-c]=this.clone(),j;j=this._getAuxPoints(c);i=j.i0;c=j.i2;h=j.j0;f=j.j1;j=j.k;e=j.x;var p=j.y;j=i.x/e;l=i.y/p;i=h.x/e;m=h.y/p;h=(f.x-e)/(1-e);f=(f.y-p)/(1-p);e=(c.x-e)/(1-e);c=(c.y-p)/(1-p);return[new CubicBezier(j,l,i,m),new CubicBezier(h,f,e,c)]};
CubicBezier.prototype.divideAtX=function(c,e){if(0>c||1<c)throw new RangeError("'x' must be a number between 0 and 1. Got "+c+" instead.");return this.divideAtT(this.getTforX(c,e))};CubicBezier.prototype.divideAtY=function(c,e){if(0>c||1<c)throw new RangeError("'y' must be a number between 0 and 1. Got "+c+" instead.");return this.divideAtT(this.getTforY(c,e))};CubicBezier.prototype.clone=function(){return new CubicBezier(this._p1.x,this._p1.y,this._p2.x,this._p2.y)};
CubicBezier.prototype.toString=function(){return"cubic-bezier("+[this._p1.x,this._p1.y,this._p2.x,this._p2.y].join(", ")+")"};CubicBezier.linear=function(){return new CubicBezier};CubicBezier.ease=function(){return new CubicBezier(0.25,0.1,0.25,1)};CubicBezier.linear=function(){return new CubicBezier(0,0,1,1)};CubicBezier.easeIn=function(){return new CubicBezier(0.42,0,1,1)};CubicBezier.easeOut=function(){return new CubicBezier(0,0,0.58,1)};
CubicBezier.easeInOut=function(){return new CubicBezier(0.42,0,0.58,1)};
var TouchScroll=function(){var c,e,h,f;function i(a){a.style.webkitTransformStyle="preserve-3d";a.style.webkitTransitionProperty="-webkit-transform"}function m(a,b,d,g){var c=a.style;null!=d&&(c.webkitTransitionDuration=d+"");null!=g&&(c.webkitTransitionTimingFunction=g+"");a.style.webkitTransform="translate("+b.e+"px, "+b.f+"px)"}function j(a){a.touches&&a.touches.length&&(a=a.touches[0]);var b=new WebKitCSSMatrix;b.e=a.pageX;b.f=a.pageY;return b}function l(a){a.e=Math.round(a.e);a.f=Math.round(a.f);
return a}function p(a,b){b=b||{};this.owner=b.owner;this.elastic=!!b.elastic;this.snapToGrid=!!b.snapToGrid;this.containerSize=null;this.maxSegments={e:1,f:1};this.currentSegment={e:0,f:0};this.scrollers={container:a,outer:null,inner:null,e:null,f:null};this._scrolls={e:!1,f:!1};this._scrollMin={e:!1,f:!1};this._scrollbars=null;this._isScrolling=!1;this._startEvent=null;this._currentOffset=new WebKitCSSMatrix;this._trackedEvents=null;this._flicking={e:!1,f:!1};this._bounces={e:null,f:null};this._animationTimeouts=
{e:[],f:[]};this._initDom();this.setupScroller()}var t=[0,0.3,0.6,1],w=[0.4,0,1,1],B=function(){if("createTouch"in document)return!0;try{return!!document.createEvent("TouchEvent").initTouchEvent}catch(a){return!1}}(),C=function(){var a=new WebKitCSSMatrix("matrix(1, 0, 0, 1, -20, -30)");return-20==a.e&&-30==a.f}();B?(c="touchstart",e="touchmove",h="touchend",f="touchcancel"):(c="mousedown",e="mousemove",h="mouseup",f="touchcancel");var u;if(C)u=function(a){a=window.getComputedStyle(a).webkitTransform;
return new WebKitCSSMatrix(a)};else{var D=/matrix\(\s*-?\d+(?:\.\d+)?\s*,\s*-?\d+(?:\.\d+)?\s*,\s*-?\d+(?:\.\d+)?\s*,\s*-?\d+(?:\.\d+)?\s*\,\s*(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)\s*\)/;u=function(a){var b=window.getComputedStyle(a).webkitTransform,a=new WebKitCSSMatrix;if(b=D.exec(b))a.e=b[1],a.f=b[2];return a}}var z=document.createElement("div");z.innerHTML='<div class="touchScrollTrack touchScrollTrackX"><div class="touchScrollHandle"></div></div><div class="touchScrollTrack touchScrollTrackY"><div class="touchScrollHandle"></div></div>';
p.handleEvent=function(a){var b=p.prototype.currentScroller;b?b.handleEvent(a):a.type===e&&a.preventDefault()};document.addEventListener(e,p.handleEvent,!1);document.addEventListener(h,p.handleEvent,!1);document.addEventListener(f,p.handleEvent,!1);p.prototype={currentScroller:null,handlerNames:{resize:"setupScroller",orientationchange:"setupScroller",webkitTransitionEnd:"onTransitionEnd",DOMSubtreeModified:"setupScroller",touchstart:"onTouchStart",mousedown:"onTouchStart",touchmove:"onTouchMove",
mousemove:"onTouchMove",touchend:"onTouchEnd",mouseup:"onTouchEnd",touchcancel:"onTouchEnd"},_initDom:function(){var a=document.createElement("div"),b=a.cloneNode(!1),d=this.scrollers.container;a.className="touchScrollInner";d.className+=" touchScroll";for(var g=0,e=d.childNodes.length;g<e;g++)a.appendChild(d.firstChild);b.appendChild(a);d.appendChild(b);this.scrollers.outer=this.scrollers.f=b;this.scrollers.inner=this.scrollers.e=a;i(b);i(a);a.style.display="inline-block";a.style.minWidth="100%";
a.style.webkitBoxSizing="border-box";var a=z.cloneNode(!0),g=a.querySelector(".touchScrollTrackX"),e=a.querySelector(".touchScrollTrackY"),A=g.firstElementChild,f=e.firstElementChild,h=a.style;h.pointerEvents="none";h.webkitTransitionProperty="opacity";h.webkitTransitionDuration="250ms";h.opacity="0";this._scrollbars={container:a,tracks:{e:g,f:e},handles:{e:A,f:f},sizes:{e:0,f:0}};i(A);i(f);d.insertBefore(a,b);"static"==window.getComputedStyle(d).position&&(d.style.position="relative");this.setupScroller();
d.addEventListener(c,this,!1);b.addEventListener("webkitTransitionEnd",this,!1);b.addEventListener("DOMSubtreeModified",this,!0);window.addEventListener("orientationchange",this,!1);window.addEventListener("resize",this,!1)},setupScroller:function(){var a=this.scrollers.outer.parentNode,a={e:parseInt(a.style.width||a.clientWidth),f:parseInt(a.style.height||a.clientHeight)},b=this.scrollers.inner,d=parseInt(b.style.width||b.clientWidth),b=parseInt(b.style.height||b.clientHeight),g=this._scrollbars,
c={e:Math.min(a.e-d,0),f:Math.min(a.f-b,0)};this.containerSize=a;this.maxSegments={e:Math.ceil(-c.e/a.e),f:Math.ceil(-c.f/a.f)};g.container.style.height=a.f+"px";this._scrollMin=c;var e=this._scrolls={e:0>c.e,f:0>c.f};this._doScroll=e.e||e.f;g.container.className="touchScrollBars";e.e&&e.f&&(g.container.className+=" touchScrollBarsBoth");g.tracks.e.style.display=e.e?"":"none";g.tracks.f.style.display=e.f?"":"none";var h=g.tracks.e.offsetWidth,f=g.tracks.f.offsetHeight;g.sizes={e:Math.round(Math.max(h*
a.e/d,25)),f:Math.round(Math.max(f*a.f/b,25))};g.handles.e.style.width=g.sizes.e+"px";g.handles.f.style.height=g.sizes.f+"px";g.maxOffsets={e:h-g.handles.e.offsetWidth,f:f-g.handles.f.offsetHeight};g.offsetRatios={e:e.e?(h-g.handles.e.offsetWidth)/c.e:0,f:e.f?(f-g.handles.f.offsetHeight)/c.f:0}},handleEvent:function(a){var b=this.handlerNames[a.type];if(b)if(this.owner&&a.type.match(/dom/i))wm.job(this.owner.getRuntimeId()+"handleEvent",1,dojo.hitch(this,function(){this[b](a)}));else this[b](a)},
onTouchStart:function(a){this._doScroll&&(this.__proto__.currentScroller=this,this._isScrolling=!1,this._trackedEvents=[],this._determineOffset(),this._trackEvent(a),this._startEventTarget=a.target,this._stopAnimations(),this._snapBack(null,0),this._startEvent=a,a.stopPropagation(),a.preventDefault())},onTouchMove:function(a){if(this._doScroll){var b=this._trackedEvents[1].matrix,b=j(a).translate(-b.e,-b.f,0),d=this._isScrolling,g=d;a.stopPropagation();a.preventDefault();g||(g=-5>=b.e||5<=b.e||-5>=
b.f||5<=b.f);g&&(d||(this._isScrolling=!0,this.showScrollbars()),this._scrollBy(b),this._trackEvent(a))}},onTouchEnd:function(a){var b=this._startEventTarget;if(!this._isScrolling&&b==a.target){for(b=a.target;1!=b.nodeType;)b=b.parentNode;var d=document.createEvent("HTMLEvents");d.initEvent("focus",!1,!1);b.dispatchEvent(d);d=document.createEvent("MouseEvent");d.initMouseEvent("click",!0,!0,a.view,1,a.screenX,a.screenY,a.clientX,a.clientY,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,a.button,null);b.dispatchEvent(d);
this.hideScrollbars()}else if(this._isScrolling&&(d=this._getLastMove(),150>=d.duration&&d.length)){var a=this._getFlickingDuration(d.speed),g=this._getFlickingLength(d.speed,a),b=d.matrix,d=g/d.length;b.e*=d;b.f*=d;this.startFlick(b,a)}this.isAnimating()||(this.snapToGrid?this._snapBackToGrid():this._snapBack()||this.hideScrollbars());delete this._startEventTarget;this._isScrolling=!1;this.__proto__.currentScroller=null},onTransitionEnd:function(a){["e","f"].forEach(function(b){a.target===this.scrollers[b]&&
(this._flicking[b]=!1)},this);this.isAnimating()||this.hideScrollbars()},isAnimating:function(){var a=this._animationTimeouts,b=this._flicking.e||this._flicking.f;return 0<a.e.length||0<a.f.length||b},scrollBy:function(a,b){this._stopAnimations();var d=new WebKitCSSMatrix;d.e=-a;d.f=-b;return this._scrollBy(d)},scrollTo:function(a,b){this._stopAnimations();var d=this._scrollMin,g=new WebKitCSSMatrix;g.e=Math.min(0,Math.max(d.e,-a));g.f=Math.min(0,Math.max(d.f,-b));d=this._currentOffset;g.e-=d.e;g.f-=
d.f;return this._scrollBy(g)},center:function(){var a=-Math.round(this._scrollMin.e/2),b=-Math.round(this._scrollMin.f/2);return this.scrollTo(a,b)},_scrollBy:function(a){var b=this._scrolls;b.e||(a.e=0);b.f||(a.f=0);var d=this._scrollMin,g=this._currentOffset,b=g.multiply(a),c=!1,e=!1,h=0,f=0;if(this.elastic){var i=g.e<d.e||0<g.e,j=g.f<d.f||0<g.f;i&&(b.e-=0.5*a.e);j&&(b.f-=0.5*a.f);if(b.e<d.e||0<b.e)c=!0,h=0<=b.e?b.e:d.e-b.e;if(b.f<d.f||0<b.f)e=!0,f=0<=b.f?b.f:d.f-b.f;if((!i||!c)&&(c||c))0<g.e?b.e/=
0.5:0<b.e?b.e*=0.5:g.e<d.e?b.e+=(d.e-g.e)/0.5:b.e<d.e&&(b.e-=0.5*(d.e-b.e));if((!j||!e)&&(e||e))0<g.f?b.f/=0.5:0<b.f?b.f*=0.5:g.f<d.f?b.f+=(d.f-g.f)/0.5:b.f<d.f&&(b.f-=0.5*(d.f-b.f))}else b.e<d.e?b.e=d.e:0<b.e&&(b.e=0),b.f<d.f?b.f=d.f:0<b.f&&(b.f=0);this._currentOffset=b;a=b.translate(0,0,0);d=b.translate(0,0,0);a.f=d.e=0;m(this.scrollers.e,a);m(this.scrollers.f,d);g=this._scrollbars.offsetRatios;a.e*=g.e;d.f*=g.f;c?this._squeezeScrollbar("e",h,0>b.e):m(this._scrollbars.handles.e,a);e?this._squeezeScrollbar("f",
f,0>b.f):m(this._scrollbars.handles.f,d);this.owner&&this.owner._onScroll&&this.owner._onScroll()},_trackEvent:function(a){var b=this._trackedEvents;b[0]=b[1];b[1]={matrix:j(a),timeStamp:a.timeStamp}},showScrollbars:function(){if(!this.snapToGrid){var a=this._scrollbars.container.style;a.webkitTransitionDuration="";a.opacity="1"}},hideScrollbars:function(){var a=this._scrollbars.container.style;a.webkitTransitionDuration="250ms";a.opacity="0"},_squeezeScrollbar:function(a,b,d,c,e){var h=this._scrollbars,
f=h.handles[a].style,i=h.sizes[a],b=Math.max(i-b,1),j=new WebKitCSSMatrix;j[a]=d?h.maxOffsets[a]:0;j["f"==a?"d":"a"]=b/i;f.webkitTransformOrigin=d?"100% 100%":"0 0";f.webkitTransitionProperty="-webkit-transform";f.webkitTransform=j;c?(f.webkitTransitionDuration=c+"ms",f.webkitTransitionTimingFunction=e,this._animationTimeouts[a].push(setTimeout(function(){f.webkitTransitionDuration=""},c))):f.webkitTransitionDuration=""},_determineOffset:function(a){var b=u(this.scrollers.e),d=u(this.scrollers.f),
b=b.multiply(d);a&&l(b);this._currentOffset=b},_stopAnimations:function(){var a=!1,b=this._scrollbars;["e","f"].forEach(function(d){this.scrollers[d].style.webkitTransitionDuration="";var c=b.handles[d];c.style.webkitTransitionDuration="";i(c);b.tracks[d].style.webkitBoxPack="";d=this._animationTimeouts[d];a=a||d.length;d.forEach(function(a){clearTimeout(a)});d.length=0},this);this._determineOffset(!0);this._scrollBy(new WebKitCSSMatrix);this._bounces.e=this._bounces.f=null;var d=this._flicking;d.e=
d.f=!1;return a},_getLastMove:function(){var a=this._trackedEvents,b=a[0],d=a[1];if(!b)return{duration:0,matrix:new WebKitCSSMatrix,length:0,speed:0};a=d.timeStamp-b.timeStamp;b=d.matrix.multiply(b.matrix.inverse());d=this._scrolls;d.e||(b.e=0);d.f||(b.f=0);d=Math.sqrt(b.e*b.e+b.f*b.f);return{duration:a,matrix:b,length:d,speed:d/a}},_getFlickingDuration:function(a){a=Math.log(0.15/a)/Math.log(0.998);return 0<a?Math.round(a):0},_getFlickingLength:function(a,b){var d=(1-Math.pow(0.998,b+1))/(1-0.998);
return a*d},startFlick:function(a,b){if(!b&&!this.snapToGrid)this._snapBack();else{var b=b||400,d=1/b,c=new CubicBezier(t[0],t[1],t[2],t[3]),e=this._scrollMin,f=this._currentOffset,h=this._scrollbars;l(a);var i=this._currentOffset.multiply(a),j=this._scrolls;if(this.snapToGrid)var p=this.maxSegments,u=this.currentSegment;var x={e:!0,f:!0};["e","f"].forEach(function(k){if(j[k]){var l=a[k],s=i[k],o=1,n=e[k],q=0;if(this.snapToGrid){var n=this.containerSize[k],q=p[k],r=u[k],v=r+(0<l?-1:1);0>v?v=0:q<v&&
(v=q);this.currentSegment[k]=v;if(v==r||!l)return this._snapBack(k,null,-r*n);q=n*=-v}this.snapToGrid?(n=(0>l?n:q)-f[k],s=0,o=n/l):(s<n?o=1-Math.max(Math.min((s-n)/a[k],1),0):s>q&&(o=1-Math.max(Math.min((s-q)/a[k],1),0)),n=o*l,s=l-n);if(!n&&!s)x[k]=this._snapBack(k);else if(o=c.getTforY(o,d),1<o?o=1:0>o&&(o=0),l=c.getPointForT(o).x,q=c.divideAtT(o),r=new WebKitCSSMatrix,r[k]=f[k],o=l*b,n&&l&&(this._flicking[k]=!0,r[k]+=n,m(this.scrollers[k],r,o+"ms",q[0]),n=r.translate(0,0,0),n[k]*=h.offsetRatios[k],
m(h.handles[k],n,o+"ms",q[0])),this.elastic&&s){n=r.translate(0,0,0);q=q[1];q._p2={x:1-w[0],y:1-w[1]};r=Math.min(0.2,100/Math.abs(s));n[k]+=s*r;l=(1-l)*b*r;this._bounces[k]={timingFunc:q,duration:l+"ms",matrix:n,bounceLength:Math.abs(s*r)};var t=this,y=this._animationTimeouts[k];y.push(setTimeout(function(){t._playQueuedBounce(k)},o));y.push(setTimeout(function(){t._snapBack(k,null);y.length=0},o+l))}}else x[k]=!1},this);!x.e&&!x.f&&this.hideScrollbars()}},_playQueuedBounce:function(a){var b=this._bounces[a];
if(b){var d=b.matrix,c=b.duration,e=b.timingFunc;m(this.scrollers[a],d,c,e);this._squeezeScrollbar(a,b.bounceLength,0>d[a],c,e);this._bounces[a]=null;return!0}return!1},_snapBack:function(a,b,d){b=null!=b?b:400;if(null==a){a=this._snapBack("e",b);d=this._snapBack("f",b);if(a=a||d){var c=this;this._animationTimeouts.f.push(setTimeout(function(){c.hideScrollbars()},b))}else this.hideScrollbars();return a}var c=this.scrollers[a],e=u(c),f=new CubicBezier(w[0],w[1],w[2],w[3]);return null!=d||e[a]<this._scrollMin[a]||
0<e[a]?(e[a]=null!=d?d:Math.max(Math.min(e[a],0),this._scrollMin[a]),this._squeezeScrollbar(a,0,0>e[a],b,f),m(c,e,b+"ms",f),Boolean(b)):!1},_snapBackToGrid:function(){var a=this._currentOffset,b=this.containerSize;["e","f"].forEach(function(d){var c=b[d],e=-Math.floor((a[d]+0.5*c)/c),f=this.maxSegments[d];0>e?e=0:f<e&&(e=f);this.currentSegment[d]=e;return this._snapBack(d,null,-e*c)},this)}};return p}();