/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.aghr;
// Generated Aug 26, 2007 4:51:35 PM by Hibernate Tools 3.2.0.b9



/**
 * CompkeyId generated by hbm2java
 */
@SuppressWarnings({"serial"})
public class CompkeyId  implements java.io.Serializable {


     private short id1;
     private short id2;

    public CompkeyId() {
    }

    public CompkeyId(short id1, short id2) {
       this.id1 = id1;
       this.id2 = id2;
    }
   
    public short getId1() {
        return this.id1;
    }
    
    public void setId1(short id1) {
        this.id1 = id1;
    }
    public short getId2() {
        return this.id2;
    }
    
    public void setId2(short id2) {
        this.id2 = id2;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CompkeyId) ) return false;
		 CompkeyId castOther = ( CompkeyId ) other; 
         
		 return (this.getId1()==castOther.getId1())
 && (this.getId2()==castOther.getId2());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId1();
         result = 37 * result + this.getId2();
         return result;
   }   


}


