/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.aghr;
// Generated Aug 26, 2007 4:51:35 PM by Hibernate Tools 3.2.0.b9



/**
 * Compkey generated by hbm2java
 */
@SuppressWarnings({"serial"})
public class Compkey  implements java.io.Serializable {


     private CompkeyId id;
     private String name;

    public Compkey() {
    }

	
    public Compkey(CompkeyId id) {
        this.id = id;
    }
    public Compkey(CompkeyId id, String name) {
       this.id = id;
       this.name = name;
    }
   
    public CompkeyId getId() {
        return this.id;
    }
    
    public void setId(CompkeyId id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


