/*
 * Copyright (C) 2010-2011 VMWare, Inc. All rights reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 

dependencies = {
	layers: [
		{
			name: "dojo.js",
			dependencies: [
			    "dojo._base.declare",
			    "dojo._base.lang",
				"dojo._base.array",
				"dojo._base.event",
				"dojo._base.connect",
				"dojo._base.html",
				"dijit._WidgetBase",
			    "dojo.i18n",
			    "dojo.rpc.JsonService",
			    "dojo.rpc.RpcService",
			    "dojo.cookie"
			]
		},
		{
			name: "studio_base.js",
			resourceName: "studio_base",
			dependencies: [
			    "dojo.number",
			    "dojo.currency",
			    "dojo.fx",			    
			    "dojo.io.iframe",
			    "dojo.string",
			    "dojo.date.stamp",
			    "dojo.date.locale",
			    "dojo.date",
			    "dojo.data.util.simpleFetch",

				"wm.studio.app.packageLoader",
			    'wm.base.components.componentList',
				"wm.base.lib.util",
				"wm.base.lib.date",
				"wm.base.lib.text",
				"wm.base.lib.types",
				"wm.base.lib.data",
			        "wm.base.lib.currencyMappings",
				"wm.base.layout.console",
				"wm.base.data.expression",
				"wm.base.data.SimpleStore",
				"wm.base.drag.capture",
				"wm.base.drag.drag",
				"wm.base.drag.layout",
/* The old datagrid is still used in DataObjectsEditor and LiveViewEditor; let it load on demand*/
				"dojox.grid._grid.scroller",
				"dojox.grid._grid.edit",
				"dojox.grid._grid.cell",
				"dojox.grid._grid.builder",
				"dojox.grid._grid.layout",
				"dojox.grid._grid.view",
				"dojox.grid._grid.drag",
				"dojox.grid._grid.lib",
				"dojox.grid._grid.views",
				"dojox.grid._grid.rows",
				"dojox.grid._grid.focus",
				"dojox.grid._grid.selection",
				"dojox.grid._grid.rowbar",
				"dojox.grid._grid.publicEvents",
				"dojox.grid.VirtualGrid",
				"dojox.grid.compat.Grid",/**/
				"dijit.form.TextBox",
				"dijit.form._FormWidget",
				"dijit._Widget",
				"dijit._base",
				"dijit._base.focus",
				"dijit._base.manager",
				"dijit._base.place",
				"dijit._base.popup",
				"dijit._base.window",
				"dijit._base.scroll",
				"dijit._base.sniff",
				"dijit._base.bidi",
				"dijit._base.typematic",
				"dijit._base.wai",
				"dijit._Templated",
				"dijit.Tooltip",
				"dijit.form.ComboBox",

				"dojo.parser",

				"dijit.form.CheckBox",
/* load on demand */
				"dijit.form.Button",
				"dijit._Container",
			        "dijit.form.DateTextBox",
				"dijit._Calendar",
				"dijit.form._DateTimeTextBox",
				"dijit.form.TimeTextBox",
				"dijit._TimePicker",
				"dijit.form.NumberTextBox",
				"dijit.form.FilteringSelect",
				"dijit.form.CurrencyTextBox",
				"dijit.form.HorizontalSlider",
				"dijit.form.VerticalSlider",
				/*	*/

				"dijit.ProgressBar",
				"dijit.form._Spinner"/*,  Load on demand
			    ,"dojox.charting.Chart2D",
				"dojox.charting.Theme",
				"dojox.charting.widget.Legend"
				*/
			]
		},
		{
			name: "studio_wm.js",
			resourceName: "studio_wm",
			layerDependencies: [
				"studio_base.js"
			],
			dependencies: [
				"wm.base.Object",
				"wm.base.Component",
				"wm.base.Component_design",
				"wm.base.Control",
				"wm.base.Control_design",
				//"wm.base.Widget",
				//"wm.base.Widget_design",
				"wm.base.Plugin",
				"wm.base.RbacPlugin",
				"wm.base.I18nPlugin",
				"wm.base.components.Page",
				"wm.base.components.HtmlLoader",
				"wm.base.components.CssLoader",
				"wm.base.components.PageLoader",
				"wm.base.components.Property",
				"wm.base.components.Publisher",
				"wm.base.components.ImageList",
				"wm.base.components.ImageList_design",
				"wm.base.components.Variable",
				"wm.base.components.Binding",
				"wm.base.components.Service",
				"wm.base.components.ServiceQueue",
				"wm.base.components.ServiceCall",
				"wm.base.components.ServiceVariable",
				"wm.base.components.LiveView",
				"wm.base.components.LiveView_design",
				"wm.base.components.LiveVariable",
				"wm.base.components.LiveVariable_design",
				"wm.base.components.NavigationCall",
				"wm.base.components.NavigationService",
				"wm.base.components.FunctionService",
				"wm.base.components.JsonRpcService",
				"wm.base.components.Security",
			        //"wm.base.components.DomMacro",
				"wm.base.components.Timer",
				"wm.base.components.LogoutVariable",
				"wm.base.components.TypeDefinition",
				"wm.base.components.DataModel",
				"wm.base.components.Query",
				"wm.base.components.JavaService",
				"wm.base.components.WebService",
				"wm.base.widget.Formatters",
				"wm.base.widget.Editors.dijit",

				"wm.base.widget.Editors.Base",
			    "wm.base.widget.Editors._NumberEditor",
			    "wm.base.widget.Editors._DateEditor",
			    "wm.base.widget.Editors._CheckBoxEditor",
			    "wm.base.widget.Editors._RadioButtonEditor",
			    "wm.base.widget.Editors._SelectEditor",


				"wm.base.widget.Editors.AbstractEditor",
				"wm.base.widget.Editors.AbstractEditor_design",
				"wm.base.widget.Editors.Text",
				"wm.base.widget.Editors.Number",
				"wm.base.widget.Editors.Date",
				"wm.base.widget.Editors.Checkbox",
				"wm.base.widget.Editors.Radiobutton",
				"wm.base.widget.Editors.Select",
				"wm.base.widget.Editors.Select_design",

				//"wm.base.widget.Box",
				//"wm.base.widget.Box_design",
				"wm.base.widget.Spacer",
				"wm.base.widget.Spacer_design",
				"wm.base.widget.layout.Layout",
				"wm.base.widget.layout.Box",
				"wm.base.widget.layout.Abs",
				"wm.base.widget.Container",
				"wm.base.widget.Container_design",
				"wm.base.widget.Panel",
				"wm.base.widget.Template",
				"wm.base.widget.Layout",
				"wm.base.widget.Content",
				"wm.base.widget.Content_design",
				"wm.base.widget.Html",
				"wm.base.widget.Bevel",
				"wm.base.widget.Bevel_design",
				"wm.base.widget.Splitter",
				"wm.base.widget.Splitter_design",
				"wm.base.widget.Layers.Decorator",
				"wm.base.widget.Layers.TabsDecorator",
				"wm.base.widget.Layers.TabsDecorator_design",
				"wm.base.widget.Layers.AccordionDecorator",
				"wm.base.widget.Layers",
				"wm.base.widget.Layers_design",
				"wm.base.widget.Buttons.Button_design",
				"wm.base.widget.Buttons.BusyButton_design", /* Reads in BusyButton.js */
				"wm.base.widget.Picture",
				"wm.base.widget.Trees.Tree_design",
				"wm.base.widget.Trees.Tree",
			    "wm.base.widget.Trees.PropertyTree",
			    "wm.base.widget.Trees.ObjectTree",
			    "wm.base.widget.Trees.DraggableTree",
			    "wm.base.widget.Trees.DebugTree",
			    "wm.base.widget.JsonStatus",
				"wm.base.widget.Label",
				"wm.base.widget.Label_design",
				"wm.base.widget.PageContainer",
				"wm.base.widget.PageContainer_design",
				"wm.base.widget.Table.builder",
				"wm.base.widget.VirtualList",
				"wm.base.widget.List",
			/**/	"wm.base.widget.FeedList",
/* Load on demand*/
				"wm.base.widget.gadget.Gadget",
				"wm.base.widget.gadget.Stocks",
				"wm.base.widget.gadget.Weather",
				"wm.base.widget.gadget.YouTube",
				"wm.base.widget.TwitterFeed",
				/**/
			/*	"wm.base.widget.Detail",
				"wm.base.widget.Form",*/
				"wm.base.widget.LiveForm",
				"wm.base.widget.LiveForm_design",
				"wm.base.widget.LivePanel",
				"wm.base.widget.LivePanel_design",
				"wm.base.widget.RelatedEditor",
				"wm.base.widget.RelatedEditor_design",
				"wm.base.widget.EditPanel",
				"wm.base.widget.EditPanel_design",
				"wm.base.widget.DataNavigator",
				"wm.base.widget.DataNavigator_design",
			/**/	"wm.base.widget.Input",
				"wm.base.widget.TextArea",
			    "wm.base.widget.Select",/**/
				"wm.base.widget.Scrim",
				"wm.base.widget.Dialogs.Dialog",
				"wm.base.widget.Dialogs.Toast",
				"wm.base.widget.Dialogs.WidgetsJsDialog",
				"wm.base.widget.Dialogs.GenericDialog",
				"wm.base.widget.Dialogs.PageDialog",
				"wm.base.widget.Dialogs.DesignableDialog",
				"wm.base.widget.Dialogs.ColorPickerDialog",
				"wm.base.widget.Dialogs.RichTextDialog",
				"wm.base.widget.Dialogs.LoadingDialog",
				"wm.base.widget.Dialogs.Dialog_design",
				"wm.base.widget.Editor",
				"wm.base.widget.FileUpload",
			    "wm.base.widget.AceEditor",
			    /*"wm.base.widget.EditArea",
				"wm.base.widget.EditArea_design",*/
				/*"wm.base.widget.Popup",*/
				"wm.base.widget.IFrame",
				"wm.base.widget.LayoutBox",
				"wm.base.widget.dijit.Dijit",
				"wm.base.widget.dijit.Dijit_design",
				"wm.base.widget.dijit.CheckBox",
				"wm.base.widget.dijit.Calendar",
				"wm.base.widget.dijit.ProgressBar",
				"wm.base.widget.dijit.ProgressBar_design",
				"wm.base.widget.dijit.Grid",
/* Load on demand*/
				"wm.base.widget.DataGrid",
				"wm.base.widget.Toolbar",
				"wm.base.widget.Ticker",
				"wm.base.widget.Ticker_design",
				"wm.base.widget.Composite",
			    //"wm.base.widget.Cards",
			/*	*/
				"wm.base.lib.date",
	        	"wm.base.lib.text",
	        	"wm.base.widget.Formatters",
	        	"wm.base.widget.Editors.dijit",
	            "wm.base.widget.Editor",
	            "wm.base.widget.RelatedEditor",
	            "wm.base.widget.Editors.Base",
	            "wm.base.widget.Editors.Text",
	            "wm.base.widget.Editors.Number",
	            "wm.base.widget.Editors.Date",
	            "wm.base.widget.Editors.Checkbox",
	            "wm.base.widget.Editors.Radiobutton",
	            "wm.base.widget.Editors.Select",
	          /**/  "wm.base.widget.Editors.Slider",
				"wm.base.widget.Editors.RichText",
/* Load on demand*/
				"wm.base.widget.DojoLightbox",
				"wm.base.widget.Dashboard",
				"wm.base.widget.Dashboard_design",
			    "dojo.dnd.Selector",
			    "dojo.dnd.Avatar",
			    "dojo.dnd.Container",
			    "dojo.dnd.Source",

				"wm.base.widget.DojoChart",
				"wm.base.widget.DojoChart_design",
				"wm.base.widget.DojoGauge",
			    "wm.base.widget.DojoFisheye",
			    "wm.base.widget.DojoFisheye_design",
			/*	*/
				"wm.base.widget.DojoGrid",
				"wm.base.widget.DojoGrid_design",
			    "wm.base.widget.DojoMenu",
			    "wm.base.widget.DojoMenu_design",
				"wm.base.widget.DojoFileUpload",				
				"wm.base.widget.DojoFlashFileUpload",				
				"wm.base.widget.ListViewer",				
				
			]
		},
		{
			name: "studio.js",
			resourceName: "studio",
			layerDependencies: [
				"studio_base.js", "studio_wm.js"
			],
			dependencies: [
				"wm.base.design.Designable",
				"wm.base.design.Surface",
				"wm.base.design.Drag",
				"wm.base.design.Wrapper",
				"wm.base.design.Designer",
				"wm.base.components.Application",
				"wm.studio.app.StudioApplication",
				"wm.studio.pages.Studio.Studio",
				"wm.studio.app.util",
				"wm.studio.app.mainNavigation",
				"wm.studio.app.keyconfig",
				"wm.studio.app.Palette",
				"wm.studio.app.binding",
				"wm.studio.app.inspector.Inspector",
				"wm.studio.app.inspector.BindInspector",
				"wm.studio.app.inspector.StyleInspector",
				"wm.studio.app.inspector.SecurityInspector",
				"wm.studio.app.inspector.ComponentInspector",
				"wm.studio.app.inspect",
				"wm.studio.app.sourcer",
				"wm.studio.app.events",
				"wm.studio.app.editcommands",
				"wm.studio.app.file",
				"wm.studio.app.css",
				"wm.studio.app.project",
				"wm.studio.app.markup",
				"wm.studio.app.actions",
				"wm.studio.app.clipboard",
				"wm.studio.app.trees",
				"wm.studio.app.menu",
				"wm.studio.app.deploy",
				"wm.studio.app.dom",
				"wm.studio.app.propertyEdit",
				"wm.studio.app.data",
				"wm.studio.app.templates.widgetTemplates",
				"wm.studio.app.dataconstants",
				"wm.studio.app.datautils",
				"wm.studio.app.servicesTree",
			    //"wm.studio.pages.Binder.Binder",
				"wm.studio.pages.BindSourceDialog.BindSourceDialog",
				/* Load on demand
				"wm.studio.pages.ImportPageDialog.ImportPageDialog",
				"wm.studio.pages.CreateLiveView.CreateLiveView",
				"wm.studio.pages.DataObjectsEditor.DataObjectsEditor",
				"wm.studio.pages.DBConnectionSettings.DBConnectionSettings",
				"wm.studio.pages.DDLDialog.DDLDialog",
				"wm.studio.pages.DeploymentDialog.DeploymentDialog",
				"wm.studio.pages.Diagnostics.Diagnostics",
				"wm.studio.pages.ImportDatabase.ImportDatabase",
				"wm.studio.pages.ImportWebService.ImportWebService",
				"wm.studio.pages.JavaEditor.JavaEditor",
				"wm.studio.pages.LiveViewEditor.LiveViewEditor",
				"wm.studio.pages.NavigationDialog.NavigationDialog",
				"wm.studio.pages.NewJavaService.NewJavaService",
				"wm.studio.pages.PreferencesPane.PreferencesPane",
				"wm.studio.pages.QueryEditor.QueryEditor",
				"wm.studio.pages.QueueDialog.QueueDialog",
				"wm.studio.pages.RegistrationDialog.RegistrationDialog",
				"wm.studio.pages.RestServiceBuilder.RestServiceBuilder",
				"wm.studio.pages.RestUrlDialog.RestUrlDialog",
				"wm.studio.pages.Security.Security",
				"wm.studio.pages.ServiceDialog.ServiceDialog",
				"wm.studio.pages.Services.Services",
				*/
			    "wm.studio.pages.Start.Start",
			    "wm.studio.pages.HandleRequiredJars.HandleRequiredJars"
			]
		}
	],

	prefixes: [
		[ "dijit", "../dijit" ],
		[ "dojox", "../dojox" ],
		[ "wm", "../../wm" ]
	]
}
