/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.adventure;
// Generated Aug 18, 2007 5:20:14 PM by Hibernate Tools 3.2.0.b9


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductDescription generated by hbm2java
 */
@SuppressWarnings({"serial", "unchecked"})
public class ProductDescription  implements java.io.Serializable {


     private int productDescriptionId;
     private String description;
     private String rowguid;
     private Date modifiedDate;
     private Set productModelProductDescriptions = new HashSet(0);

    public ProductDescription() {
    }

	
    public ProductDescription(int productDescriptionId, String description, String rowguid, Date modifiedDate) {
        this.productDescriptionId = productDescriptionId;
        this.description = description;
        this.rowguid = rowguid;
        this.modifiedDate = modifiedDate;
    }
    public ProductDescription(int productDescriptionId, String description, String rowguid, Date modifiedDate, Set productModelProductDescriptions) {
       this.productDescriptionId = productDescriptionId;
       this.description = description;
       this.rowguid = rowguid;
       this.modifiedDate = modifiedDate;
       this.productModelProductDescriptions = productModelProductDescriptions;
    }
   
    public int getProductDescriptionId() {
        return this.productDescriptionId;
    }
    
    public void setProductDescriptionId(int productDescriptionId) {
        this.productDescriptionId = productDescriptionId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Set getProductModelProductDescriptions() {
        return this.productModelProductDescriptions;
    }
    
    public void setProductModelProductDescriptions(Set productModelProductDescriptions) {
        this.productModelProductDescriptions = productModelProductDescriptions;
    }




}


