/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.wavemaker.runtime.data.sample.adventure;

// Generated Aug 18, 2007 5:20:14 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductCategory generated by hbm2java
 */
@SuppressWarnings({ "serial", "unchecked" })
public class ProductCategory implements java.io.Serializable {

    private int productCategoryId;

    private ProductCategory productCategory;

    private String name;

    private String rowguid;

    private Date modifiedDate;

    private Set products = new HashSet(0);

    private Set productCategories = new HashSet(0);

    public ProductCategory() {
    }

    public ProductCategory(int productCategoryId, String name, String rowguid, Date modifiedDate) {
        this.productCategoryId = productCategoryId;
        this.name = name;
        this.rowguid = rowguid;
        this.modifiedDate = modifiedDate;
    }

    public ProductCategory(int productCategoryId, ProductCategory productCategory, String name, String rowguid, Date modifiedDate, Set products,
        Set productCategories) {
        this.productCategoryId = productCategoryId;
        this.productCategory = productCategory;
        this.name = name;
        this.rowguid = rowguid;
        this.modifiedDate = modifiedDate;
        this.products = products;
        this.productCategories = productCategories;
    }

    public int getProductCategoryId() {
        return this.productCategoryId;
    }

    public void setProductCategoryId(int productCategoryId) {
        this.productCategoryId = productCategoryId;
    }

    public ProductCategory getProductCategory() {
        return this.productCategory;
    }

    public void setProductCategory(ProductCategory productCategory) {
        this.productCategory = productCategory;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRowguid() {
        return this.rowguid;
    }

    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }

    public Date getModifiedDate() {
        return this.modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    public Set getProducts() {
        return this.products;
    }

    public void setProducts(Set products) {
        this.products = products;
    }

    public Set getProductCategories() {
        return this.productCategories;
    }

    public void setProductCategories(Set productCategories) {
        this.productCategories = productCategories;
    }

}
