/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.wavemaker.runtime.data.sample.adventure;
// Generated Aug 18, 2007 5:20:14 PM by Hibernate Tools 3.2.0.b9


import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SalesOrderHeader generated by hbm2java
 */
@SuppressWarnings({"serial", "unchecked"})
public class SalesOrderHeader  implements java.io.Serializable {


     private int salesOrderId;
     private Address addressByShipToAddressId;
     private Address addressByBillToAddressId;
     private Customer customer;
     private byte revisionNumber;
     private Date orderDate;
     private Date dueDate;
     private Date shipDate;
     private byte status;
     private boolean onlineOrderFlag;
     private String salesOrderNumber;
     private String purchaseOrderNumber;
     private String accountNumber;
     private String shipMethod;
     private String creditCardApprovalCode;
     private BigDecimal subTotal;
     private BigDecimal taxAmt;
     private BigDecimal freight;
     private BigDecimal totalDue;
     private Clob comment;
     private String rowguid;
     private Date modifiedDate;
     private Set salesOrderDetails = new HashSet(0);

    public SalesOrderHeader() {
    }

	
    public SalesOrderHeader(int salesOrderId, Customer customer, byte revisionNumber, Date orderDate, Date dueDate, byte status, boolean onlineOrderFlag, String salesOrderNumber, String shipMethod, BigDecimal subTotal, BigDecimal taxAmt, BigDecimal freight, BigDecimal totalDue, String rowguid, Date modifiedDate) {
        this.salesOrderId = salesOrderId;
        this.customer = customer;
        this.revisionNumber = revisionNumber;
        this.orderDate = orderDate;
        this.dueDate = dueDate;
        this.status = status;
        this.onlineOrderFlag = onlineOrderFlag;
        this.salesOrderNumber = salesOrderNumber;
        this.shipMethod = shipMethod;
        this.subTotal = subTotal;
        this.taxAmt = taxAmt;
        this.freight = freight;
        this.totalDue = totalDue;
        this.rowguid = rowguid;
        this.modifiedDate = modifiedDate;
    }
    public SalesOrderHeader(int salesOrderId, Address addressByShipToAddressId, Address addressByBillToAddressId, Customer customer, byte revisionNumber, Date orderDate, Date dueDate, Date shipDate, byte status, boolean onlineOrderFlag, String salesOrderNumber, String purchaseOrderNumber, String accountNumber, String shipMethod, String creditCardApprovalCode, BigDecimal subTotal, BigDecimal taxAmt, BigDecimal freight, BigDecimal totalDue, Clob comment, String rowguid, Date modifiedDate, Set salesOrderDetails) {
       this.salesOrderId = salesOrderId;
       this.addressByShipToAddressId = addressByShipToAddressId;
       this.addressByBillToAddressId = addressByBillToAddressId;
       this.customer = customer;
       this.revisionNumber = revisionNumber;
       this.orderDate = orderDate;
       this.dueDate = dueDate;
       this.shipDate = shipDate;
       this.status = status;
       this.onlineOrderFlag = onlineOrderFlag;
       this.salesOrderNumber = salesOrderNumber;
       this.purchaseOrderNumber = purchaseOrderNumber;
       this.accountNumber = accountNumber;
       this.shipMethod = shipMethod;
       this.creditCardApprovalCode = creditCardApprovalCode;
       this.subTotal = subTotal;
       this.taxAmt = taxAmt;
       this.freight = freight;
       this.totalDue = totalDue;
       this.comment = comment;
       this.rowguid = rowguid;
       this.modifiedDate = modifiedDate;
       this.salesOrderDetails = salesOrderDetails;
    }
   
    public int getSalesOrderId() {
        return this.salesOrderId;
    }
    
    public void setSalesOrderId(int salesOrderId) {
        this.salesOrderId = salesOrderId;
    }
    public Address getAddressByShipToAddressId() {
        return this.addressByShipToAddressId;
    }
    
    public void setAddressByShipToAddressId(Address addressByShipToAddressId) {
        this.addressByShipToAddressId = addressByShipToAddressId;
    }
    public Address getAddressByBillToAddressId() {
        return this.addressByBillToAddressId;
    }
    
    public void setAddressByBillToAddressId(Address addressByBillToAddressId) {
        this.addressByBillToAddressId = addressByBillToAddressId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public byte getRevisionNumber() {
        return this.revisionNumber;
    }
    
    public void setRevisionNumber(byte revisionNumber) {
        this.revisionNumber = revisionNumber;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public Date getShipDate() {
        return this.shipDate;
    }
    
    public void setShipDate(Date shipDate) {
        this.shipDate = shipDate;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public boolean isOnlineOrderFlag() {
        return this.onlineOrderFlag;
    }
    
    public void setOnlineOrderFlag(boolean onlineOrderFlag) {
        this.onlineOrderFlag = onlineOrderFlag;
    }
    public String getSalesOrderNumber() {
        return this.salesOrderNumber;
    }
    
    public void setSalesOrderNumber(String salesOrderNumber) {
        this.salesOrderNumber = salesOrderNumber;
    }
    public String getPurchaseOrderNumber() {
        return this.purchaseOrderNumber;
    }
    
    public void setPurchaseOrderNumber(String purchaseOrderNumber) {
        this.purchaseOrderNumber = purchaseOrderNumber;
    }
    public String getAccountNumber() {
        return this.accountNumber;
    }
    
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }
    public String getShipMethod() {
        return this.shipMethod;
    }
    
    public void setShipMethod(String shipMethod) {
        this.shipMethod = shipMethod;
    }
    public String getCreditCardApprovalCode() {
        return this.creditCardApprovalCode;
    }
    
    public void setCreditCardApprovalCode(String creditCardApprovalCode) {
        this.creditCardApprovalCode = creditCardApprovalCode;
    }
    public BigDecimal getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(BigDecimal subTotal) {
        this.subTotal = subTotal;
    }
    public BigDecimal getTaxAmt() {
        return this.taxAmt;
    }
    
    public void setTaxAmt(BigDecimal taxAmt) {
        this.taxAmt = taxAmt;
    }
    public BigDecimal getFreight() {
        return this.freight;
    }
    
    public void setFreight(BigDecimal freight) {
        this.freight = freight;
    }
    public BigDecimal getTotalDue() {
        return this.totalDue;
    }
    
    public void setTotalDue(BigDecimal totalDue) {
        this.totalDue = totalDue;
    }
    public Clob getComment() {
        return this.comment;
    }
    
    public void setComment(Clob comment) {
        this.comment = comment;
    }
    public String getRowguid() {
        return this.rowguid;
    }
    
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Set getSalesOrderDetails() {
        return this.salesOrderDetails;
    }
    
    public void setSalesOrderDetails(Set salesOrderDetails) {
        this.salesOrderDetails = salesOrderDetails;
    }




}


