/*
 *  Copyright (C) 2009 WaveMaker Software, Inc.
 *
 *  This file is part of the WaveMaker Server Runtime.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.wavemaker.runtime.data.sample.adventure;

// Generated Aug 18, 2007 5:20:14 PM by Hibernate Tools 3.2.0.b9

import java.sql.Clob;
import java.util.Date;

/**
 * VproductModelCatalogDescriptionId generated by hbm2java
 */
@SuppressWarnings("serial")
public class VproductModelCatalogDescriptionId implements java.io.Serializable {

    private int productModelId;

    private String name;

    private Clob summary;

    private Clob manufacturer;

    private String copyright;

    private String productUrl;

    private String warrantyPeriod;

    private String warrantyDescription;

    private String noOfYears;

    private String maintenanceDescription;

    private String wheel;

    private String saddle;

    private String pedal;

    private Clob bikeFrame;

    private String crankset;

    private String pictureAngle;

    private String pictureSize;

    private String productPhotoId;

    private String material;

    private String color;

    private String productLine;

    private String style;

    private String riderExperience;

    private String rowguid;

    private Date modifiedDate;

    public VproductModelCatalogDescriptionId() {
    }

    public VproductModelCatalogDescriptionId(int productModelId, String name, String rowguid, Date modifiedDate) {
        this.productModelId = productModelId;
        this.name = name;
        this.rowguid = rowguid;
        this.modifiedDate = modifiedDate;
    }

    public VproductModelCatalogDescriptionId(int productModelId, String name, Clob summary, Clob manufacturer, String copyright, String productUrl,
        String warrantyPeriod, String warrantyDescription, String noOfYears, String maintenanceDescription, String wheel, String saddle,
        String pedal, Clob bikeFrame, String crankset, String pictureAngle, String pictureSize, String productPhotoId, String material, String color,
        String productLine, String style, String riderExperience, String rowguid, Date modifiedDate) {
        this.productModelId = productModelId;
        this.name = name;
        this.summary = summary;
        this.manufacturer = manufacturer;
        this.copyright = copyright;
        this.productUrl = productUrl;
        this.warrantyPeriod = warrantyPeriod;
        this.warrantyDescription = warrantyDescription;
        this.noOfYears = noOfYears;
        this.maintenanceDescription = maintenanceDescription;
        this.wheel = wheel;
        this.saddle = saddle;
        this.pedal = pedal;
        this.bikeFrame = bikeFrame;
        this.crankset = crankset;
        this.pictureAngle = pictureAngle;
        this.pictureSize = pictureSize;
        this.productPhotoId = productPhotoId;
        this.material = material;
        this.color = color;
        this.productLine = productLine;
        this.style = style;
        this.riderExperience = riderExperience;
        this.rowguid = rowguid;
        this.modifiedDate = modifiedDate;
    }

    public int getProductModelId() {
        return this.productModelId;
    }

    public void setProductModelId(int productModelId) {
        this.productModelId = productModelId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Clob getSummary() {
        return this.summary;
    }

    public void setSummary(Clob summary) {
        this.summary = summary;
    }

    public Clob getManufacturer() {
        return this.manufacturer;
    }

    public void setManufacturer(Clob manufacturer) {
        this.manufacturer = manufacturer;
    }

    public String getCopyright() {
        return this.copyright;
    }

    public void setCopyright(String copyright) {
        this.copyright = copyright;
    }

    public String getProductUrl() {
        return this.productUrl;
    }

    public void setProductUrl(String productUrl) {
        this.productUrl = productUrl;
    }

    public String getWarrantyPeriod() {
        return this.warrantyPeriod;
    }

    public void setWarrantyPeriod(String warrantyPeriod) {
        this.warrantyPeriod = warrantyPeriod;
    }

    public String getWarrantyDescription() {
        return this.warrantyDescription;
    }

    public void setWarrantyDescription(String warrantyDescription) {
        this.warrantyDescription = warrantyDescription;
    }

    public String getNoOfYears() {
        return this.noOfYears;
    }

    public void setNoOfYears(String noOfYears) {
        this.noOfYears = noOfYears;
    }

    public String getMaintenanceDescription() {
        return this.maintenanceDescription;
    }

    public void setMaintenanceDescription(String maintenanceDescription) {
        this.maintenanceDescription = maintenanceDescription;
    }

    public String getWheel() {
        return this.wheel;
    }

    public void setWheel(String wheel) {
        this.wheel = wheel;
    }

    public String getSaddle() {
        return this.saddle;
    }

    public void setSaddle(String saddle) {
        this.saddle = saddle;
    }

    public String getPedal() {
        return this.pedal;
    }

    public void setPedal(String pedal) {
        this.pedal = pedal;
    }

    public Clob getBikeFrame() {
        return this.bikeFrame;
    }

    public void setBikeFrame(Clob bikeFrame) {
        this.bikeFrame = bikeFrame;
    }

    public String getCrankset() {
        return this.crankset;
    }

    public void setCrankset(String crankset) {
        this.crankset = crankset;
    }

    public String getPictureAngle() {
        return this.pictureAngle;
    }

    public void setPictureAngle(String pictureAngle) {
        this.pictureAngle = pictureAngle;
    }

    public String getPictureSize() {
        return this.pictureSize;
    }

    public void setPictureSize(String pictureSize) {
        this.pictureSize = pictureSize;
    }

    public String getProductPhotoId() {
        return this.productPhotoId;
    }

    public void setProductPhotoId(String productPhotoId) {
        this.productPhotoId = productPhotoId;
    }

    public String getMaterial() {
        return this.material;
    }

    public void setMaterial(String material) {
        this.material = material;
    }

    public String getColor() {
        return this.color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getProductLine() {
        return this.productLine;
    }

    public void setProductLine(String productLine) {
        this.productLine = productLine;
    }

    public String getStyle() {
        return this.style;
    }

    public void setStyle(String style) {
        this.style = style;
    }

    public String getRiderExperience() {
        return this.riderExperience;
    }

    public void setRiderExperience(String riderExperience) {
        this.riderExperience = riderExperience;
    }

    public String getRowguid() {
        return this.rowguid;
    }

    public void setRowguid(String rowguid) {
        this.rowguid = rowguid;
    }

    public Date getModifiedDate() {
        return this.modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof VproductModelCatalogDescriptionId)) {
            return false;
        }
        VproductModelCatalogDescriptionId castOther = (VproductModelCatalogDescriptionId) other;

        return this.getProductModelId() == castOther.getProductModelId()
            && (this.getName() == castOther.getName() || this.getName() != null && castOther.getName() != null
                && this.getName().equals(castOther.getName()))
            && (this.getSummary() == castOther.getSummary() || this.getSummary() != null && castOther.getSummary() != null
                && this.getSummary().equals(castOther.getSummary()))
            && (this.getManufacturer() == castOther.getManufacturer() || this.getManufacturer() != null && castOther.getManufacturer() != null
                && this.getManufacturer().equals(castOther.getManufacturer()))
            && (this.getCopyright() == castOther.getCopyright() || this.getCopyright() != null && castOther.getCopyright() != null
                && this.getCopyright().equals(castOther.getCopyright()))
            && (this.getProductUrl() == castOther.getProductUrl() || this.getProductUrl() != null && castOther.getProductUrl() != null
                && this.getProductUrl().equals(castOther.getProductUrl()))
            && (this.getWarrantyPeriod() == castOther.getWarrantyPeriod() || this.getWarrantyPeriod() != null
                && castOther.getWarrantyPeriod() != null && this.getWarrantyPeriod().equals(castOther.getWarrantyPeriod()))
            && (this.getWarrantyDescription() == castOther.getWarrantyDescription() || this.getWarrantyDescription() != null
                && castOther.getWarrantyDescription() != null && this.getWarrantyDescription().equals(castOther.getWarrantyDescription()))
            && (this.getNoOfYears() == castOther.getNoOfYears() || this.getNoOfYears() != null && castOther.getNoOfYears() != null
                && this.getNoOfYears().equals(castOther.getNoOfYears()))
            && (this.getMaintenanceDescription() == castOther.getMaintenanceDescription() || this.getMaintenanceDescription() != null
                && castOther.getMaintenanceDescription() != null && this.getMaintenanceDescription().equals(castOther.getMaintenanceDescription()))
            && (this.getWheel() == castOther.getWheel() || this.getWheel() != null && castOther.getWheel() != null
                && this.getWheel().equals(castOther.getWheel()))
            && (this.getSaddle() == castOther.getSaddle() || this.getSaddle() != null && castOther.getSaddle() != null
                && this.getSaddle().equals(castOther.getSaddle()))
            && (this.getPedal() == castOther.getPedal() || this.getPedal() != null && castOther.getPedal() != null
                && this.getPedal().equals(castOther.getPedal()))
            && (this.getBikeFrame() == castOther.getBikeFrame() || this.getBikeFrame() != null && castOther.getBikeFrame() != null
                && this.getBikeFrame().equals(castOther.getBikeFrame()))
            && (this.getCrankset() == castOther.getCrankset() || this.getCrankset() != null && castOther.getCrankset() != null
                && this.getCrankset().equals(castOther.getCrankset()))
            && (this.getPictureAngle() == castOther.getPictureAngle() || this.getPictureAngle() != null && castOther.getPictureAngle() != null
                && this.getPictureAngle().equals(castOther.getPictureAngle()))
            && (this.getPictureSize() == castOther.getPictureSize() || this.getPictureSize() != null && castOther.getPictureSize() != null
                && this.getPictureSize().equals(castOther.getPictureSize()))
            && (this.getProductPhotoId() == castOther.getProductPhotoId() || this.getProductPhotoId() != null
                && castOther.getProductPhotoId() != null && this.getProductPhotoId().equals(castOther.getProductPhotoId()))
            && (this.getMaterial() == castOther.getMaterial() || this.getMaterial() != null && castOther.getMaterial() != null
                && this.getMaterial().equals(castOther.getMaterial()))
            && (this.getColor() == castOther.getColor() || this.getColor() != null && castOther.getColor() != null
                && this.getColor().equals(castOther.getColor()))
            && (this.getProductLine() == castOther.getProductLine() || this.getProductLine() != null && castOther.getProductLine() != null
                && this.getProductLine().equals(castOther.getProductLine()))
            && (this.getStyle() == castOther.getStyle() || this.getStyle() != null && castOther.getStyle() != null
                && this.getStyle().equals(castOther.getStyle()))
            && (this.getRiderExperience() == castOther.getRiderExperience() || this.getRiderExperience() != null
                && castOther.getRiderExperience() != null && this.getRiderExperience().equals(castOther.getRiderExperience()))
            && (this.getRowguid() == castOther.getRowguid() || this.getRowguid() != null && castOther.getRowguid() != null
                && this.getRowguid().equals(castOther.getRowguid()))
            && (this.getModifiedDate() == castOther.getModifiedDate() || this.getModifiedDate() != null && castOther.getModifiedDate() != null
                && this.getModifiedDate().equals(castOther.getModifiedDate()));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getProductModelId();
        result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
        result = 37 * result + (getSummary() == null ? 0 : this.getSummary().hashCode());
        result = 37 * result + (getManufacturer() == null ? 0 : this.getManufacturer().hashCode());
        result = 37 * result + (getCopyright() == null ? 0 : this.getCopyright().hashCode());
        result = 37 * result + (getProductUrl() == null ? 0 : this.getProductUrl().hashCode());
        result = 37 * result + (getWarrantyPeriod() == null ? 0 : this.getWarrantyPeriod().hashCode());
        result = 37 * result + (getWarrantyDescription() == null ? 0 : this.getWarrantyDescription().hashCode());
        result = 37 * result + (getNoOfYears() == null ? 0 : this.getNoOfYears().hashCode());
        result = 37 * result + (getMaintenanceDescription() == null ? 0 : this.getMaintenanceDescription().hashCode());
        result = 37 * result + (getWheel() == null ? 0 : this.getWheel().hashCode());
        result = 37 * result + (getSaddle() == null ? 0 : this.getSaddle().hashCode());
        result = 37 * result + (getPedal() == null ? 0 : this.getPedal().hashCode());
        result = 37 * result + (getBikeFrame() == null ? 0 : this.getBikeFrame().hashCode());
        result = 37 * result + (getCrankset() == null ? 0 : this.getCrankset().hashCode());
        result = 37 * result + (getPictureAngle() == null ? 0 : this.getPictureAngle().hashCode());
        result = 37 * result + (getPictureSize() == null ? 0 : this.getPictureSize().hashCode());
        result = 37 * result + (getProductPhotoId() == null ? 0 : this.getProductPhotoId().hashCode());
        result = 37 * result + (getMaterial() == null ? 0 : this.getMaterial().hashCode());
        result = 37 * result + (getColor() == null ? 0 : this.getColor().hashCode());
        result = 37 * result + (getProductLine() == null ? 0 : this.getProductLine().hashCode());
        result = 37 * result + (getStyle() == null ? 0 : this.getStyle().hashCode());
        result = 37 * result + (getRiderExperience() == null ? 0 : this.getRiderExperience().hashCode());
        result = 37 * result + (getRowguid() == null ? 0 : this.getRowguid().hashCode());
        result = 37 * result + (getModifiedDate() == null ? 0 : this.getModifiedDate().hashCode());
        return result;
    }

}
